### ISSUE TITLE
Bug: NameError: name 'LifeSpanScope' is not defined

### ISSUE THREAD

**Issue by 4n1qz5skwv** [litestar-org/litestar#1472]
### Description

This **NameError** occurs when trying to mount a **Litestar asgi** App. 

Works fine if you remove the `bar_app` or replace `bar_app` asgi with another `starlette`  app.

### URL to code causing the issue

app never started... so no url.

### MCVE

```python
from litestar import Litestar, get
from litestar import asgi
from starlette.applications import Starlette
from starlette.requests import Request
from starlette.responses import PlainTextResponse
from starlette.routing import Route


@get("/")
async def litestar_index() -> str:
    return "Hello, world!"


async def starlette_index(request: Request) -> PlainTextResponse:
    return PlainTextResponse({"app": "starlette"})


foo_app = asgi(path="/foo", is_mount=True)(Starlette(routes=[Route("/", starlette_index)]))
bar_app = asgi(path="/bar", is_mount=True)(Litestar(route_handlers=[litestar_index]))

app = Litestar(route_handlers=[foo_app, bar_app])

if __name__ == '__main__':
    import uvicorn

    uvicorn.run('foobar:app', port=8000)
```

### Steps to reproduce

```bash
1. try to run the code.
2. It will fail to start.
```

### Logs

```bash
Traceback (most recent call last):
  File "---\app\foobar.py", line 21, in <module>
    app = Litestar(route_handlers=[foo_app, bar_app])
  File "venv\lib\site-packages\litestar\app.py", line 436, in __init__
    self.register(route_handler)
  File "venv\lib\site-packages\litestar\app.py", line 531, in register
    route_handler.on_registration()
  File "venv\lib\site-packages\litestar\handlers\base.py", line 374, in on_registration
    self._validate_handler_function()
  File "venv\lib\site-packages\litestar\handlers\asgi_handlers.py", line 79, in _validate_handler_function
    if not self.parsed_fn_signature.return_type.is_subclass_of(NoneType):
  File "venv\lib\site-packages\litestar\handlers\base.py", line 158, in parsed_fn_signature
    self._parsed_fn_signature = ParsedSignature.from_fn(
  File "venv\lib\site-packages\litestar\types\parsed_signature.py", line 227, in from_fn
    fn_type_hints = get_fn_type_hints(fn, namespace=signature_namespace)
  File "venv\lib\site-packages\litestar\utils\signature_parsing.py", line 65, in get_fn_type_hints
    return get_type_hints(fn_to_inspect, globalns=namespace, include_extras=True)
  File "venv\lib\site-packages\typing_extensions.py", line 936, in get_type_hints
    hint = typing.get_type_hints(
  File "python\Python\lib\typing.py", line 1870, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "python\Python\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "python\Python\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'LifeSpanScope' is not defined
```
```


### Litestar Version

2.0.0a3

### Platform

- [ ] Linux
- [ ] Mac
- [X] Windows
- [ ] Other (Please specify in the description above)

**Comment by Goldziher** [comment]
testing this (iOS - no windows for me)

**Comment by Goldziher** [comment]
Fix PR added. Thanks for the reproduction!

**Comment by Goldziher** [comment]
PR merged and issue is fixed on the main branch. It will be in the next alpha version, or you can directly use main for now.
