### ISSUE TITLE
KeyError when configuring DTO

### ISSUE THREAD

**Issue by jhert0** [litestar-org/litestar#1837]
### Description

I'm getting a KeyError on startup that seems to be coming from my DTO I create with SQLAlchemyDTO. The property that is being called out in the exception is a relationship. If I try to exclude it from the DTO I still get the error.

### Steps to reproduce

```
1. Create a model for SQLAlchemy that includes a relationship to another model.
2. Create a DTO for the one that has the relationship.
3. Start the app.
```

### Logs

```bash
Traceback (most recent call last):
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/bin/litestar", line 8, in <module>
    sys.exit(run_cli())
             ^^^^^^^^^
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/litestar/__main__.py", line 6, in run_cli
    litestar_group()
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/litestar/cli/_utils.py", line 231, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/litestar/cli/commands/core.py", line 113, in run_command
    env = cast(LitestarEnv, ctx.obj())
                            ^^^^^^^^^
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/litestar/cli/main.py", line 51, in <lambda>
    ctx.obj = lambda: LitestarEnv.from_env(app_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/litestar/cli/_utils.py", line 113, in from_env
    loaded_app = _load_app_from_path(app_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/litestar/cli/_utils.py", line 254, in _load_app_from_path
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jhert/src/bankroller/services/vault/vault/main.py", line 24, in <module>
    app = Litestar(
          ^^^^^^^^^
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/litestar/app.py", line 432, in __init__
    self.register(route_handler)
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/litestar/app.py", line 570, in register
    route_handler.on_registration(self)
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/litestar/handlers/http_handlers/base.py", line 482, in on_registration
    super().on_registration(app)
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/litestar/handlers/base.py", line 393, in on_registration
    self._init_handler_dtos()
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/litestar/handlers/base.py", line 372, in _init_handler_dtos
    return_dto.on_registration(HandlerContext("return", str(self), self.parsed_fn_signature.return_type))
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/litestar/dto/factory/abc.py", line 171, in on_registration
    backend = cls._type_backend_map.setdefault(key, backend_type(backend_context))
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/litestar/dto/factory/_backends/abc.py", line 124, in __init__
    self.parsed_field_definitions = self.parse_model(context.model_type, context.config.exclude)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/litestar/dto/factory/_backends/abc.py", line 162, in parse_model
    for field_definition in self.context.field_definition_generator(model_type):
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/litestar/contrib/sqlalchemy/dto.py", line 195, in generate_field_definitions
    yield from cls.handle_orm_descriptor(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 946, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jhert/.cache/pypoetry/virtualenvs/vault-ePQ6d2du-py3.11/lib/python3.11/site-packages/litestar/contrib/sqlalchemy/dto.py", line 86, in _
    if (parsed_type := model_type_hints[key]).origin is Mapped:
                       ~~~~~~~~~~~~~~~~^^^^^
KeyError: 'prices'
```

### Litestar Version

2.0.0b1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by provinzkraut** [comment]
Hey @jhert0 thanks for reporting this. Can you provide a reproducible example for the behaviour you're describing?

**Comment by peterschutt** [comment]
As @provinzkraut suggested, an example that properly reproduces the issue is going to be a big help. Not only for identifying the source of the issue, but also for assessing whether there is some pattern of usage that we need to consider more thoroughly.

The `SQLAlchemyDTO` is tested against relationships in these tests:

- https://github.com/litestar-org/litestar/blob/a1842a000f2f3639bc9d1b0875ae31da050689cd/tests/contrib/sqlalchemy/test_dto.py#L229
- https://github.com/litestar-org/litestar/blob/a1842a000f2f3639bc9d1b0875ae31da050689cd/tests/contrib/sqlalchemy/test_dto.py#L270
- https://github.com/litestar-org/litestar/blob/a1842a000f2f3639bc9d1b0875ae31da050689cd/tests/contrib/sqlalchemy/test_dto.py#L374
- https://github.com/litestar-org/litestar/blob/a1842a000f2f3639bc9d1b0875ae31da050689cd/tests/contrib/sqlalchemy/test_dto.py#L412
- https://github.com/litestar-org/litestar/blob/a1842a000f2f3639bc9d1b0875ae31da050689cd/tests/contrib/sqlalchemy/test_dto.py#L449

So perhaps you can look at those as an example of how to build an MCVE for the DTO and help us to determine what is different in your case.

Given that the exception originates as a key error from the type hints extracted from the model in this line:

```
    if (parsed_type := model_type_hints[key]).origin is Mapped:
```

I'm speculating that the relationship might be declared on the model without a type annotation. E.g.,:

```py
class Market(Base):
    prices = relationship("Price")
```

Instead of something like:

```py
class Market(Base):
    prices: Mapped[list[Price]] = relationship()
```

Speculation on my part though, so I'll wait to hear from you before going any further.

Cheers.

**Comment by jhert0** [comment]
Yes that was it, I was missing the type hint. Thank you.
