### ISSUE TITLE
Bug: Throwing TypeError when partial=True 

### ISSUE THREAD

**Issue by su-shubham** [litestar-org/litestar#1953]
### Description

When overriding dto for patch dto it works well at the controller level but the problematic thing is `PATCH` request should be partially updated so using partial=True throws a TypeError.

### MCVE

```python
from __future__ import annotations

from dataclasses import dataclass

from litestar import Controller, Litestar, patch, post, put
from litestar.dto.factory import DTOConfig, DTOData
from litestar.dto.factory.stdlib.dataclass import DataclassDTO


@dataclass
class Person:
    name: str
    age: int
    email: str
    id: int


class ReadDTO(DataclassDTO[Person]):
    config = DTOConfig(exclude={"email"})


class WriteDTO(DataclassDTO[Person]):
    config = DTOConfig(exclude={"id"})


class PatchDTO(DataclassDTO[Person]):
    config = DTOConfig(exclude={"id"}, partial=True)


class PersonController(Controller):
    dto = WriteDTO
    return_dto = ReadDTO

    @post("/person", sync_to_thread=False)
    def create_person(self, data: DTOData[Person]) -> Person:
        # Logic for persisting the person goes here
        return data.create_instance(id=1)

    @put("/person/{person_id:int}", sync_to_thread=False)
    def update_person(self, person_id: int, data: DTOData[Person]) -> Person:
        # Usually the Person would be retrieved from a database
        person = Person(id=person_id, name="John", age=50, email="email_of_john@example.com")
        return data.update_instance(person)

    @patch("/person/{person_id:int}", dto=PatchDTO, sync_to_thread=False)
    def patch_person(self, person_id: int, data: DTOData[Person]) -> Person:
        # Usually the Person would be retrieved from a database
        person = Person(id=person_id, name="John", age=50, email="email_of_john@example.com")
        return data.update_instance(person)


app = Litestar(route_handlers=[PersonController])
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots
![image](https://github.com/litestar-org/litestar/assets/75021117/372bb310-d362-491d-983b-e47e3244104c)

### Logs

```bash
Traceback (most recent call last):
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\routes\http.py", line 77, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\routes\http.py", line 129, in _get_response_for_request
    response = await self._call_handler_function(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\routes\http.py", line 158, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\routes\http.py", line 205, in _get_response_data
    data = route_handler.fn.value(**parsed_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\openapi\controller.py", line 215, in swagger_ui
    return ASGIResponse(body=self.render_swagger_ui(request), media_type=MediaType.HTML)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\openapi\controller.py", line 261, in render_swagger_ui
    schema = self.get_schema_from_request(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\openapi\controller.py", line 86, in get_schema_from_request
    return request.app.openapi_schema
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\app.py", line 536, in openapi_schema
    self.update_openapi_schema()
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\app.py", line 792, in update_openapi_schema
    path_item, created_operation_ids = create_path_item(
                                       ^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\_openapi\path_item.py", line 110, in create_path_item
    request_body = create_request_body(
                   ^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\_openapi\request_body.py", line 28, in create_request_body
    schema = dto.create_openapi_schema("data", str(route_handler), schema_creator)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\dto\factory\abc.py", line 184, in create_openapi_schema
    return cls._get_backend(dto_for, handler_id).create_openapi_schema(schema_creator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\dto\factory\_backends\abc.py", line 334, in create_openapi_schema
    return schema_creator.for_field(SignatureField.create(self.annotation))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\_openapi\schema_generation\schema.py", line 411, in for_field
    result = self.for_struct_class(field.field_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\_openapi\schema_generation\schema.py", line 654, in for_struct_class
    properties={
               ^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\_openapi\schema_generation\schema.py", line 655, in <dictcomp>
    field.encode_name: self.for_field(SignatureField.create(field.type, field.encode_name))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\_openapi\schema_generation\schema.py", line 405, in for_field
    result = self.for_union_field(field)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\_openapi\schema_generation\schema.py", line 467, in for_union_field
    return Schema(one_of=sort_schemas_and_references(list(map(self.for_field, field.children or []))))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\_openapi\schema_generation\utils.py", line 17, in sort_schemas_and_references
    return sorted(values, key=lambda value: value.type if isinstance(value, Schema) else value.ref)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'OpenAPIType'
Traceback (most recent call last):
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\middleware\exceptions\middleware.py", line 157, in __call__
    await self.app(scope, receive, send)
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\routes\http.py", line 77, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\routes\http.py", line 129, in _get_response_for_request
    response = await self._call_handler_function(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\routes\http.py", line 158, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\routes\http.py", line 205, in _get_response_data
    data = route_handler.fn.value(**parsed_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\openapi\controller.py", line 215, in swagger_ui
    return ASGIResponse(body=self.render_swagger_ui(request), media_type=MediaType.HTML)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\openapi\controller.py", line 261, in render_swagger_ui
    schema = self.get_schema_from_request(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\openapi\controller.py", line 86, in get_schema_from_request
    return request.app.openapi_schema
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\app.py", line 536, in openapi_schema
    self.update_openapi_schema()
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\app.py", line 792, in update_openapi_schema
    path_item, created_operation_ids = create_path_item(
                                       ^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\_openapi\path_item.py", line 110, in create_path_item
    request_body = create_request_body(
                   ^^^^^^^^^^^^^^^^^^^^
  File "D:\lite-experiment\lite-dto\venv\Lib\site-packages\litestar\_openapi\schema_generation\utils.py", line 17, in sort_schemas_and_references
    return sorted(values, key=lambda value: value.type if isinstance(value, Schema) else value.ref)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'OpenAPIType'
```

### Litestar Version

2.0.0b2

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/1953">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1953/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1953/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment]
Hi. You mean that what you'd expect is that the DTO for patch is with partial by default? 

What's the bug otherwise?

**Comment by cofin** [comment]
I think have seen this same issue in fullstack.   Any use of `PatchDTO` raises an error similar to above.

**Comment by su-shubham** [comment]
@Goldziher Whenever we use partial=True at Patch request it throws an error. Applicable for both overriding and no overriding.

**Comment by Goldziher** [comment]
i see. ok i will check this out!

**Comment by Goldziher** [comment]
This is working on main - fix has been merged. Please test @su-shubham.

**Comment by su-shubham** [comment]
I have no idea but partially executing means sometimes showing the above error,sometimes this error, and sometimes the result🤔.
![image](https://github.com/litestar-org/litestar/assets/75021117/8de0777f-74e1-4696-8f03-a578ab2ea757)

**Comment by Goldziher** [comment]
> @Goldziher I have no idea but partially executing means sometimes showing the above error, sometimes this error, and sometimes the result🤔.
> 
> I think now --debug causing the issue of showing the above error. ![image](https://user-images.githubusercontent.com/75021117/254792884-8de0777f-74e1-4696-8f03-a578ab2ea757.png)

have you tested main?

**Comment by su-shubham** [comment]
Tested on main. It `resolved😊`!
