### ISSUE TITLE
Bug: TypeError: parse_url_encoded_dict() got some positional-only arguments passed as keyword arguments: 'qs' and 'parse_numbers'

### ISSUE THREAD

**Issue by euri10** [litestar-org/litestar#2020]
### Description

New litestar install
```
❯ poetry add git+https://github.com/litestar-org/litestar.git

Updating dependencies
Resolving dependencies... (1.2s)

Package operations: 7 installs, 0 updates, 0 removals

  • Installing python-dateutil (2.8.2)
  • Installing faker (19.1.0)
  • Installing fast-query-parsers (1.0.1)
  • Installing msgspec (0.17.0)
  • Installing multidict (6.0.4)
  • Installing polyfactory (2.6.2)
  • Installing litestar (2.0.0beta2 dc8790e)
```
leads to this error filling the form below:
```
Traceback (most recent call last):
  File "/home/lotso/.cache/pypoetry/virtualenvs/abdul-5gvWwsxX-py3.11/lib/python3.11/site-packages/litestar/middleware/exceptions/middleware.py", line 157, in __call__
    await self.app(scope, receive, send)
  File "/home/lotso/.cache/pypoetry/virtualenvs/abdul-5gvWwsxX-py3.11/lib/python3.11/site-packages/litestar/routes/http.py", line 77, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/.cache/pypoetry/virtualenvs/abdul-5gvWwsxX-py3.11/lib/python3.11/site-packages/litestar/routes/http.py", line 129, in _get_response_for_request
    response = await self._call_handler_function(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/.cache/pypoetry/virtualenvs/abdul-5gvWwsxX-py3.11/lib/python3.11/site-packages/litestar/routes/http.py", line 158, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/.cache/pypoetry/virtualenvs/abdul-5gvWwsxX-py3.11/lib/python3.11/site-packages/litestar/routes/http.py", line 182, in _get_response_data
    kwargs["data"] = await kwargs["data"]
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/.cache/pypoetry/virtualenvs/abdul-5gvWwsxX-py3.11/lib/python3.11/site-packages/litestar/_kwargs/extractors.py", line 363, in extract_url_encoded_extractor
    else parse_url_encoded_form_data(await connection.body())
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/.cache/pypoetry/virtualenvs/abdul-5gvWwsxX-py3.11/lib/python3.11/site-packages/litestar/_parsers.py", line 24, in parse_url_encoded_form_data
    return parse_url_encoded_dict(qs=encoded_data, parse_numbers=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: parse_url_encoded_dict() got some positional-only arguments passed as keyword arguments: 'qs' and 'parse_numbers'
Traceback (most recent call last):
  File "/home/lotso/.cache/pypoetry/virtualenvs/abdul-5gvWwsxX-py3.11/lib/python3.11/site-packages/litestar/middleware/exceptions/middleware.py", line 157, in __call__
    await self.app(scope, receive, send)
  File "/home/lotso/.cache/pypoetry/virtualenvs/abdul-5gvWwsxX-py3.11/lib/python3.11/site-packages/litestar/routes/http.py", line 77, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/.cache/pypoetry/virtualenvs/abdul-5gvWwsxX-py3.11/lib/python3.11/site-packages/litestar/routes/http.py", line 129, in _get_response_for_request
    response = await self._call_handler_function(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/.cache/pypoetry/virtualenvs/abdul-5gvWwsxX-py3.11/lib/python3.11/site-packages/litestar/routes/http.py", line 158, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/.cache/pypoetry/virtualenvs/abdul-5gvWwsxX-py3.11/lib/python3.11/site-packages/litestar/routes/http.py", line 182, in _get_response_data
    kwargs["data"] = await kwargs["data"]
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/.cache/pypoetry/virtualenvs/abdul-5gvWwsxX-py3.11/lib/python3.11/site-packages/litestar/_kwargs/extractors.py", line 363, in extract_url_encoded_extractor
    else parse_url_encoded_form_data(await connection.body())
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/.cache/pypoetry/virtualenvs/abdul-5gvWwsxX-py3.11/lib/python3.11/site-packages/litestar/_parsers.py", line 24, in parse_url_encoded_form_data
    return parse_url_encoded_dict(qs=encoded_data, parse_numbers=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: parse_url_encoded_dict() got some positional-only arguments passed as keyword arguments: 'qs' and 'parse_numbers'
INFO:     127.0.0.1:51104 - "POST /auth/login HTTP/1.1" 500 Internal Server Error```

### URL to code causing the issue

_No response_

### MCVE

```python
@dataclass
class LoginFormData:
    username: str
    password: str
    captcha: str


@post("/login", name="login_post")
async def login_post(
    request: Request,
    conn: BuildPgConnection,
    app_settings: AppSettings,
    data: Annotated[LoginFormData, Body(media_type=RequestEncodingType.URL_ENCODED)],
) -> Template:
    try:
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

  • Installing litestar (2.0.0beta2 dc8790e)

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by provinzkraut** [comment]
I believe this is related to a recent change in `fast-query-parsers`. @Goldziher?

Not sure why this hasn't been caught in our tests though.

**Comment by Goldziher** [comment]
Hmm yes, seems that maturin is positional only. 

Can you remove `parse_numbers=` and keep the args?

**Comment by provinzkraut** [comment]
> Hmm yes, seems that maturin is positional only.

It does support it. I have a fix read to go for `fast-query-parsers`. PR incoming.

**Comment by euri10** [comment]
> I believe this is related to a recent change in `fast-query-parsers`. @Goldziher?
> 
> Not sure why this hasn't been caught in our tests though.

I dont know the code well enough but it seems to me that test_kwargs only uses https://github.com/litestar-org/litestar/blob/dc8790e63f0e90f1650042558a9be620bf4b1eae/tests/unit/test_kwargs/__init__.py#L4-L8 so there are no tests on other possible attrs, dataclass forms etc, might be wrong on this again I dont know the source well enough

**Comment by provinzkraut** [comment]
This should resolve it: https://github.com/litestar-org/fast-query-parsers/pull/18 by allowing positional, as well as keyword arguments.

**Comment by provinzkraut** [comment]
> so there are no tests on other possible attrs, dataclass forms etc, might be wrong on this again I dont know the source well enough

The issue is at the calling site of `parse_url_encoded_form_data`, which we definitely run during tests. We'll have to investigate that one.

https://github.com/litestar-org/litestar/blob/dc8790e63f0e90f1650042558a9be620bf4b1eae/litestar/_parsers.py#L24

**Comment by euri10** [comment]
yep, sorry I was referring to https://github.com/litestar-org/litestar/issues/2019 and https://github.com/litestar-org/litestar/issues/1997, wrong topic
