### ISSUE TITLE
Bug: Swagger generation fails when using pydantic BaseModel

### ISSUE THREAD

**Issue by Xemnas0** [litestar-org/litestar#2133]
### Description

Litestar version: 2.0.0rc1
Pydantic version: 2.1.1

(coming from #2101)

Swagger creation fails if multiple responses are defined on the endpoint definition and the responses subclass pydantic.BaseModel.

However, if I use dataclasses (as the code below)

```python
from litestar import Litestar, get, status_codes
from litestar.openapi import ResponseSpec
from dataclasses import dataclass


@dataclass
class User:
    id: str


@dataclass
class NotFoundResponse:
    message: str


@get(
    path="/user/{user_id:str}",
    responses={
        status_codes.HTTP_200_OK: ResponseSpec(data_container=User),
        status_codes.HTTP_404_NOT_FOUND: ResponseSpec(data_container=NotFoundResponse),
    },
)
def get_user(user_id: str) -> User:
    if user_id == "null":
        return NotFoundResponse(message="not found")
    return User(id=user_id)


app = Litestar(route_handlers=[get_user])
```

The result is the following

![image](https://github.com/litestar-org/litestar/assets/26822543/d43a9a28-65ab-4a95-b6d4-f11e9c8023a1)

### MCVE

```python
from litestar import Litestar, get, status_codes
from litestar.openapi import ResponseSpec
from pydantic import BaseModel


class User(BaseModel):
    id: str


class NotFoundResponse(BaseModel):
    message: str


@get(
    path="/user/{user_id:str}",
    responses={
        status_codes.HTTP_200_OK: ResponseSpec(data_container=User),
        status_codes.HTTP_404_NOT_FOUND: ResponseSpec(data_container=NotFoundResponse),
    },
)
def get_user(user_id: str) -> User:
    if user_id == "null":
        return NotFoundResponse(message="not found")
    return User(id=user_id)


app = Litestar(route_handlers=[get_user])
```

### Steps to reproduce

```bash
1. `litestar run`
2. Go to localhost:8000/schema/swagger
```

### Logs

```bash
INFO:     Started server process [66800]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
ERROR - 2023-08-01 16:44:26,204 - litestar - config - exception raised on http connection to route /schema/swagger

Traceback (most recent call last):
  File "/home/myuser/projects/litestar-test/.venv/lib/python3.10/site-packages/litestar/serialization/msgspec_hooks.py", line 141, in encode_json
    return msgspec.json.encode(value, enc_hook=serializer) if serializer else _msgspec_json_encoder.encode(value)
  File "/home/myuser/projects/litestar-test/.venv/lib/python3.10/site-packages/litestar/serialization/msgspec_hooks.py", line 88, in default_serializer
    raise TypeError(f"Unsupported type: {type(value)!r}")
TypeError: Unsupported type: <class 'app.User'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/myuser/projects/litestar-test/.venv/lib/python3.10/site-packages/litestar/middleware/exceptions/middleware.py", line 157, in __call__
    await self.app(scope, receive, send)
  File "/home/myuser/projects/litestar-test/.venv/lib/python3.10/site-packages/litestar/routes/http.py", line 77, in handle
    response = await self._get_response_for_request(
  File "/home/myuser/projects/litestar-test/.venv/lib/python3.10/site-packages/litestar/routes/http.py", line 129, in _get_response_for_request
    response = await self._call_handler_function(
  File "/home/myuser/projects/litestar-test/.venv/lib/python3.10/site-packages/litestar/routes/http.py", line 158, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
  File "/home/myuser/projects/litestar-test/.venv/lib/python3.10/site-packages/litestar/routes/http.py", line 204, in _get_response_data
    data = route_handler.fn.value(**parsed_kwargs)
  File "/home/myuser/projects/litestar-test/.venv/lib/python3.10/site-packages/litestar/openapi/controller.py", line 209, in swagger_ui
    return ASGIResponse(body=self.render_swagger_ui(request), media_type=MediaType.HTML)
  File "/home/myuser/projects/litestar-test/.venv/lib/python3.10/site-packages/litestar/openapi/controller.py", line 275, in render_swagger_ui
    spec: {encode_json(schema.to_schema()).decode("utf-8")},
  File "/home/myuser/projects/litestar-test/.venv/lib/python3.10/site-packages/litestar/serialization/msgspec_hooks.py", line 143, in encode_json
    raise SerializationException(str(msgspec_error)) from msgspec_error
litestar.exceptions.base_exceptions.SerializationException: Unsupported type: <class 'app.User'>
Traceback (most recent call last):
  File "/home/myuser/projects/litestar-test/.venv/lib/python3.10/site-packages/litestar/serialization/msgspec_hooks.py", line 141, in encode_json
    return msgspec.json.encode(value, enc_hook=serializer) if serializer else _msgspec_json_encoder.encode(value)
  File "/home/myuser/projects/litestar-test/.venv/lib/python3.10/site-packages/litestar/serialization/msgspec_hooks.py", line 88, in default_serializer
    raise TypeError(f"Unsupported type: {type(value)!r}")
TypeError: Unsupported type: <class 'app.User'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/myuser/projects/litestar-test/.venv/lib/python3.10/site-packages/litestar/middleware/exceptions/middleware.py", line 157, in __call__
    await self.app(scope, receive, send)
  File "/home/myuser/projects/litestar-test/.venv/lib/python3.10/site-packages/litestar/routes/http.py", line 77, in handle
    response = await self._get_response_for_request(
  File "/home/myuser/projects/litestar-test/.venv/lib/python3.10/site-packages/litestar/routes/http.py", line 129, in _get_response_for_request
    response = await self._call_handler_function(
  File "/home/myuser/projects/litestar-test/.venv/lib/python3.10/site-packages/litestar/routes/http.py", line 158, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
  File "/home/myuser/projects/litestar-test/.venv/lib/python3.10/site-packages/litestar/routes/http.py", line 204, in _get_response_data
    data = route_handler.fn.value(**parsed_kwargs)
  File "/home/myuser/projects/litestar-test/.venv/lib/python3.10/site-packages/litestar/openapi/controller.py", line 209, in swagger_ui
    return ASGIResponse(body=self.render_swagger_ui(request), media_type=MediaType.HTML)
  File "/home/myuser/projects/litestar-test/.venv/lib/python3.10/site-packages/litestar/openapi/controller.py", line 275, in render_swagger_ui
    spec: {encode_json(schema.to_schema()).decode("utf-8")},
  File "/home/myuser/projects/litestar-test/.venv/lib/python3.10/site-packages/litestar/serialization/msgspec_hooks.py", line 143, in encode_json
    raise SerializationException(str(msgspec_error)) from msgspec_error
litestar.exceptions.base_exceptions.SerializationException: Unsupported type: <class 'app.User'>
INFO:     127.0.0.1:44104 - "GET /schema/swagger HTTP/1.1" 500 Internal Server Error
```

### Litestar Version

2.0.0rc1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2133">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2133/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2133/pledge.svg">
</picture>
</a>

**Comment by Xemnas0** [comment]
From a little investigation, it seems to happen because
_create_examples_for_field()_ in litestar/_openapi/schema_generation/examples.py
creates an instance of the class without serializing.

Modifying the function like this works, but I don't think it's the proper way to do it. I'm not familiar with the codebase

```python
def create_examples_for_field(field: FieldDefinition) -> list[Example]:
    """Create an OpenAPI Example instance.

    Args:
        field: A signature field.

    Returns:
        A list including a single example.
    """
    try:
        field_meta = _create_field_meta(replace(field, annotation=_normalize_example_value(field.annotation)))
        value = Factory.get_field_value(field_meta)
        # Start new code
        value = value.model_dump() if hasattr(value, "model_dump") else value
        # End new code
        return [Example(description=f"Example {field.name} value", value=value).to_schema()]
    except ParameterException:
        return []
```

**Comment by guacs** [comment]
This is the same as the issue discussed [here](https://discord.com/channels/919193495116337154/1134060657629745304). @JacobCoffee or @Xemnas0 , could you edit the title to reflect that the bug is swagger generation fails when using a pydantic BaseModel?

**Comment by Goldziher** [comment]
@guacs you now should have privileges to do this
