### ISSUE TITLE
Bug: url-encoded request data is attempted to be parsed as json

### ISSUE THREAD

**Issue by i404788** [litestar-org/litestar#2174]
### Description

When using the URL_ENCODED body annotation litestar still attempts to decode it as json causing a ClientException (400 status).

### MCVE

```python
# all.py
from typing import Annotated, Any
from pydantic import parse_obj_as
from litestar import Controller, get, post, put, patch, delete
from litestar.enums import RequestEncodingType
from litestar.params import Body
from litestar.exceptions import HTTPException

class allController(Controller):
    path = "/"
    @post(path="/")
    async def post_all(self,  data: Annotated[Any, Body(media_type=RequestEncodingType.URL_ENCODED)], ) -> None:
        print(data)

# main.py
from litestar import Litestar
from .models import *
from .all import *

app = Litestar(debug=True)
app.register(allController)
```

```sh
curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' -d "Action=ListVerifiedEmailAddresses&Version=2010-12-01" http://127.0.0.1:8000/
```

### Steps to reproduce

```bash
Run python with `LITESTAR_APP=main:app litestar run -d --port 8001` then run curl command.
```

### Logs

```bash
INFO:     127.0.0.1:59566 - "POST / HTTP/1.1" 400 Bad Request
ERROR - 2023-08-17 15:45:46,390 - litestar - config - exception raised on http connection to route /

Traceback (most recent call last):
  File "/home/null/mambaforge/lib/python3.10/site-packages/litestar/serialization/msgspec_hooks.py", line 186, in decode_json
    return _msgspec_json_decoder.decode(value)
msgspec.DecodeError: JSON is malformed: invalid character (byte 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/null/mambaforge/lib/python3.10/site-packages/litestar/routes/http.py", line 184, in _get_response_data
    kwargs["data"] = await kwargs["data"]
  File "/home/null/mambaforge/lib/python3.10/site-packages/litestar/_kwargs/extractors.py", line 272, in json_extractor
    return await connection.json()
  File "/home/null/mambaforge/lib/python3.10/site-packages/litestar/connection/request.py", line 107, in json
    self._json = self.scope["_json"] = decode_json(body or b"null", type_decoders=self.route_handler.resolve_type_decoders())  # type: ignore[typeddict-unknown-key]
  File "/home/null/mambaforge/lib/python3.10/site-packages/litestar/serialization/msgspec_hooks.py", line 191, in decode_json
    raise SerializationException(str(msgspec_error)) from msgspec_error
litestar.exceptions.base_exceptions.SerializationException: JSON is malformed: invalid character (byte 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/null/mambaforge/lib/python3.10/site-packages/litestar/middleware/exceptions/middleware.py", line 159, in __call__
    await self.app(scope, receive, send)
  File "/home/null/mambaforge/lib/python3.10/site-packages/litestar/routes/http.py", line 79, in handle
    response = await self._get_response_for_request(
  File "/home/null/mambaforge/lib/python3.10/site-packages/litestar/routes/http.py", line 131, in _get_response_for_request
    response = await self._call_handler_function(
  File "/home/null/mambaforge/lib/python3.10/site-packages/litestar/routes/http.py", line 160, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
  File "/home/null/mambaforge/lib/python3.10/site-packages/litestar/routes/http.py", line 186, in _get_response_data
    raise ClientException(str(e)) from e
litestar.exceptions.http_exceptions.ClientException: 400: JSON is malformed: invalid character (byte 0)
Traceback (most recent call last):
  File "/home/null/mambaforge/lib/python3.10/site-packages/litestar/serialization/msgspec_hooks.py", line 186, in decode_json
    return _msgspec_json_decoder.decode(value)
msgspec.DecodeError: JSON is malformed: invalid character (byte 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/null/mambaforge/lib/python3.10/site-packages/litestar/routes/http.py", line 184, in _get_response_data
    kwargs["data"] = await kwargs["data"]
  File "/home/null/mambaforge/lib/python3.10/site-packages/litestar/_kwargs/extractors.py", line 272, in json_extractor
    return await connection.json()
  File "/home/null/mambaforge/lib/python3.10/site-packages/litestar/connection/request.py", line 107, in json
    self._json = self.scope["_json"] = decode_json(body or b"null", type_decoders=self.route_handler.resolve_type_decoders())  # type: ignore[typeddict-unknown-key]
  File "/home/null/mambaforge/lib/python3.10/site-packages/litestar/serialization/msgspec_hooks.py", line 191, in decode_json
    raise SerializationException(str(msgspec_error)) from msgspec_error
litestar.exceptions.base_exceptions.SerializationException: JSON is malformed: invalid character (byte 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/null/mambaforge/lib/python3.10/site-packages/litestar/middleware/exceptions/middleware.py", line 159, in __call__
    await self.app(scope, receive, send)
  File "/home/null/mambaforge/lib/python3.10/site-packages/litestar/routes/http.py", line 79, in handle
    response = await self._get_response_for_request(
  File "/home/null/mambaforge/lib/python3.10/site-packages/litestar/routes/http.py", line 131, in _get_response_for_request
    response = await self._call_handler_function(
  File "/home/null/mambaforge/lib/python3.10/site-packages/litestar/routes/http.py", line 160, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
  File "/home/null/mambaforge/lib/python3.10/site-packages/litestar/routes/http.py", line 186, in _get_response_data
    raise ClientException(str(e)) from e
litestar.exceptions.http_exceptions.ClientException: 400: JSON is malformed: invalid character (byte 0)
```

### Litestar Version

2.0.0rc1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2174">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2174/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2174/pledge.svg">
</picture>
</a>

**Comment by i404788** [comment]
Update, this example seems to work just fine, I'm trying to find the differences now: https://github.com/litestar-org/litestar/blob/3c6575711c72d353ee36b16d6f55b74088545fd0/docs/examples/request_data/request_data_4.py#L18
