### ISSUE TITLE
Bug: OpenAPI generation throws exception when using an optional path value

### ISSUE THREAD

**Issue by smithk86** [litestar-org/litestar#2222]
### Description

I think I found an OpenAPI generation bug when using multiple paths on the same route with an optional path parameter value. The first call to /schema always fails with a 500 status code. Subsequent calls are successful but do not contain the problem route. I assume this is due to caching.

Another interesting thing I found is that if you load /schema/openapi.json first, you still get a 500 the first time but the cache is built with the route defined for subsequent calls. Although, the parameter is listed as a query parameter instead of a path parameter.

Thanks!
Kyle

### MCVE

```python
from litestar import Litestar, get, MediaType

@get(path=["/", "/{message:str}"], media_type=MediaType.TEXT, sync_to_thread=False)
def route(message: str | None) -> str:
    if message:
        return message
    return "no message"

app = Litestar(route_handlers=[route])
```

### Steps to reproduce

```bash
* Run app: litestar run
* Load http://localhost:8000/schema
* Get 500 Internal Server Error
```

### Logs

```bash
Traceback (most recent call last):
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 79, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 131, in _get_response_for_request
    response = await self._call_handler_function(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 160, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 206, in _get_response_data
    data = route_handler.fn.value(**parsed_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/openapi/controller.py", line 197, in root
    return ASGIResponse(body=render_method(request), media_type=MediaType.HTML)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/openapi/controller.py", line 357, in render_redoc
    schema = self.get_schema_from_request(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/openapi/controller.py", line 85, in get_schema_from_request
    return request.app.openapi_schema
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/app.py", line 562, in openapi_schema
    self.update_openapi_schema()
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/app.py", line 818, in update_openapi_schema
    path_item, created_operation_ids = create_path_item(
                                       ^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/_openapi/path_item.py", line 97, in create_path_item
    create_parameter_for_handler(
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/_openapi/parameters.py", line 214, in create_parameter_for_handler
    for parameter in get_recursive_handler_parameters(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/_openapi/parameters.py", line 131, in get_recursive_handler_parameters
    create_parameter(
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/_openapi/parameters.py", line 87, in create_parameter
    result = schema_creator.for_field_definition(replace(field_definition, annotation=path_parameter.type))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/_openapi/schema_generation/schema.py", line 265, in for_field_definition
    result = self.for_optional_field(field_definition)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/_openapi/schema_generation/schema.py", line 306, in for_optional_field
    annotation=make_non_optional_union(field_definition.annotation),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/utils/typing.py", line 175, in make_non_optional_union
    return cast("UnionT", Union[args])  # pyright: ignore
                          ~~~~~^^^^^^
  File "/home/ksmith/.pyenv/versions/3.11.4/lib/python3.11/typing.py", line 355, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ksmith/.pyenv/versions/3.11.4/lib/python3.11/typing.py", line 478, in __getitem__
    return self._getitem(self, parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksmith/.pyenv/versions/3.11.4/lib/python3.11/typing.py", line 685, in Union
    raise TypeError("Cannot take a Union of no types.")
TypeError: Cannot take a Union of no types.
Traceback (most recent call last):
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/middleware/exceptions/middleware.py", line 191, in __call__
    await self.app(scope, receive, send)
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 79, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 131, in _get_response_for_request
    response = await self._call_handler_function(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 160, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 206, in _get_response_data
    data = route_handler.fn.value(**parsed_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/openapi/controller.py", line 197, in root
    return ASGIResponse(body=render_method(request), media_type=MediaType.HTML)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/openapi/controller.py", line 357, in render_redoc
    schema = self.get_schema_from_request(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/openapi/controller.py", line 85, in get_schema_from_request
    return request.app.openapi_schema
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/app.py", line 562, in openapi_schema
    self.update_openapi_schema()
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/app.py", line 818, in update_openapi_schema
    path_item, created_operation_ids = create_path_item(
                                       ^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/_openapi/path_item.py", line 97, in create_path_item
    create_parameter_for_handler(
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/_openapi/parameters.py", line 214, in create_parameter_for_handler
    for parameter in get_recursive_handler_parameters(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/_openapi/parameters.py", line 131, in get_recursive_handler_parameters
    create_parameter(
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/_openapi/parameters.py", line 87, in create_parameter
    result = schema_creator.for_field_definition(replace(field_definition, annotation=path_parameter.type))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/_openapi/schema_generation/schema.py", line 265, in for_field_definition
    result = self.for_optional_field(field_definition)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/_openapi/schema_generation/schema.py", line 306, in for_optional_field
    annotation=make_non_optional_union(field_definition.annotation),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/mvce/.venv/lib/python3.11/site-packages/litestar/utils/typing.py", line 175, in make_non_optional_union
    return cast("UnionT", Union[args])  # pyright: ignore
                          ~~~~~^^^^^^
  File "/home/ksmith/.pyenv/versions/3.11.4/lib/python3.11/typing.py", line 355, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ksmith/.pyenv/versions/3.11.4/lib/python3.11/typing.py", line 478, in __getitem__
    return self._getitem(self, parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksmith/.pyenv/versions/3.11.4/lib/python3.11/typing.py", line 685, in Union
    raise TypeError("Cannot take a Union of no types.")
TypeError: Cannot take a Union of no types.
```

### Litestar Version

2.0.1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2222">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2222/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2222/pledge.svg">
</picture>
</a>

**Comment by ThinksFast** [comment]
+1:  I noticed this behavior yesterday, I'm also getting a 500 on first page load of the schema paths

**Comment by Goldziher** [comment]
Can you give a minimum reproduction?
