### ISSUE TITLE
Bug: `--app-dir` option does not work/fails during autodiscovery.

### ISSUE THREAD

**Issue by sykloid** [litestar-org/litestar#2266]
### Description

Hi! I'm trying to use the Litestar CLI with the following invocation:

`litestar --app-dir src --app litestar_test:app`

with the following project structure:

```
.
├── pyproject.toml
└── src
    └── litestar_test
        └── __init__.py
```

where `__init__.py` contains:

```python
from litestar import Litestar

app = Litestar()
```

However I'm getting the following error:

```
Using Litestar app from env: 'litestar_test:app'
Traceback (most recent call last):
  File "/home/sykloid/src/litestar_test/.venv/bin/litestar", line 8, in <module>
    sys.exit(run_cli())
             ^^^^^^^^^
  File "/home/sykloid/src/litestar_test/.venv/lib/python3.11/site-packages/litestar/__main__.py", line 6, in run_cli
    litestar_group()
  File "/home/sykloid/src/litestar_test/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sykloid/src/litestar_test/.venv/lib/python3.11/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sykloid/src/litestar_test/.venv/lib/python3.11/site-packages/click/core.py", line 1077, in main
    with self.make_context(prog_name, args, **extra) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sykloid/src/litestar_test/.venv/lib/python3.11/site-packages/litestar/cli/_utils.py", line 237, in make_context
    self._prepare(ctx)
  File "/home/sykloid/src/litestar_test/.venv/lib/python3.11/site-packages/litestar/cli/_utils.py", line 218, in _prepare    env = ctx\.obj = LitestarEnv.from_env(ctx.params.get("app_path"), ctx.params.get("app_dir"))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sykloid/src/litestar_test/.venv/lib/python3.11/site-packages/litestar/cli/_utils.py", line 114, in from_env    loaded_ap\p = _load_app_from_path(app_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sykloid/src/litestar_test/.venv/lib/python3.11/site-packages/litestar/cli/_utils.py", line 290, in _load_app_from_path
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sykloid/.rye/py/cpython@3.11.3/install/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'litestar_test'
```

My guess is that this is because even though `sys.path.append(app_dir)` is happening in `litestar.cli.main.litestar_group`, the call to `litestar.cli._utils.LitestarEnv.from_env` is happening before that, and `app_dir` is not added to `sys.path` in that case.

I was able to verify that the following changes worked:

1. Manually adding `src` to `PYTHONPATH` (obviously)
2. Modifying `litestar.cli._utils.LitestarEnv.from_env` to take an extra parameter `app_dir`, and calling it as `env = ctx.obj = LitestarEnv.from_env(ctx.params.get("app_path"), ctx.params.get("app_dir"))` in `LitestarExtensionGroup.prepare`

### Steps to reproduce

```bash
`litestar --app-dir src --app litestar_test:app info`
```

### Litestar Version

2.0.1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2266">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2266/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2266/pledge.svg">
</picture>
</a>

**Comment by abdulhaq-e** [comment]
Thanks for reporting this and the PR.

I just want to add a tip in case you didn't know about it. You can add `litestar_test` as a local package by including it in the `pyproject.toml` file (under `[tool.poetry]`):

```toml
packages = [
{ include = "litestar_test", from = 'src/' }
]
```

Then if you run `poetry install`, you would be able to use the cli without needing `--app-dir`.
