### ISSUE TITLE
Bug: `url_for` template callable doesn't work in Jinja macros

### ISSUE THREAD

**Issue by geeshta** [litestar-org/litestar#2461]
### Description

When using the `url_for`  template callable inside of a Jinja macro, an exception is thrown.  It seems that the `request` context variable is not injected, which is responsible for resolving URLs.

See MCVE:
```
<li>{{ item.name }} - <a href="{{ url_for('item_detail', id=item.id) }}">Detail</a></li>
```
This is inside of a Jinja macro which gets called inside of another template. This leads to an error. If you delete the `<a>` tag, the macro will work properly.
```
<a href="{{ url_for('item_list') }}">Back to list</a>
```
This is directly inside of a template string and doesn't raise an error.

### MCVE

```python
from jinja2.environment import Environment
from jinja2.loaders import DictLoader
from litestar import Litestar, get
from litestar.contrib.jinja import JinjaTemplateEngine
from litestar.response import Template
from litestar.template import TemplateConfig

macros = r"""
{% macro list_items(items) %}
  <ul>
  {% for item in items %}
    <li>{{ item.name }} - <a href="{{ url_for('item_detail', id=item.id) }}">Detail</a></li>
  {% endfor %}
  </ul>
{% endmacro %}
"""

item_list_template = r"""
{% import "macros.html.j2" as render %}
<html>
  <head></head>
  <body>
    {{ render.list_items(items) }}
  </body>
</html>
"""

item_detail_template = r"""
<html>
  <head></head>
  <body>
    <div>
      <strong>{{ item.id }}: </strong>{{ item.name }}
    </div>
    <div>
      <a href="{{ url_for('item_list') }}">Back to list</a>
    </div>
  </body>
</html>
"""


jinja_env = Environment(
    loader=DictLoader(
        {
            "macros.html.j2": macros,
            "item_list.html.j2": item_list_template,
            "item_detail.html.j2": item_detail_template,
        }
    )
)
template_config = TemplateConfig(engine=JinjaTemplateEngine.from_environment(jinja_env))

items = [
    {"id": 1, "name": "Alice"},
    {"id": 2, "name": "Bob"},
    {"id": 3, "name": "Charlie"},
]


@get("/", name="item_list")
async def item_list() -> Template:
    return Template("item_list.html.j2", context={"items": items})


@get("/{id:int}", name="item_detail")
async def item_detail(id: int) -> Template:
    item = [item for item in items if item["id"] == id][0]
    return Template("item_detail.html.j2", context={"item": item})


app = Litestar(route_handlers=[item_list, item_detail], template_config=template_config)
```

### Steps to reproduce

```bash
1. Run the MCVE app
2. Navigate to `/`
3. An error is raised
4. When navigating to `/1`, no error is raised
5. If you delete the `<a>` tag inside of the macro and navigate to `/`, no error is raised
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Logs

```bash
ERROR - 2023-10-16 21:31:07,972585630 - litestar - middleware - exception raised on http connection to route /

Traceback (most recent call last):
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/litestar/middleware/exceptions/middleware.py", line 191, in __call__
    await self.app(scope, receive, send)
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 79, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 131, in _get_response_for_request
    response = await self._call_handler_function(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 164, in _call_handler_function
    response: ASGIApp = await route_handler.to_response(app=scope["app"], data=response_data, request=request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/litestar/handlers/http_handlers/base.py", line 494, in to_response
    return await response_handler(app=app, data=data, request=request)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/litestar/handlers/http_handlers/_utils.py", line 153, in handler
    return response.to_asgi_response(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/litestar/response/template.py", line 130, in to_asgi_response
    body = template.render(**context).encode(self.encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 6, in top-level template code
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "<template>", line 5, in template
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/litestar/template/base.py", line 42, in url_for
    return context["request"].app.route_reverse(route_name, **path_parameters)
           ~~~~~~~^^^^^^^^^^^
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/jinja2/runtime.py", line 331, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Traceback (most recent call last):
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/litestar/middleware/exceptions/middleware.py", line 191, in __call__
    await self.app(scope, receive, send)
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 79, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 131, in _get_response_for_request
    response = await self._call_handler_function(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 164, in _call_handler_function
    response: ASGIApp = await route_handler.to_response(app=scope["app"], data=response_data, request=request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/litestar/handlers/http_handlers/base.py", line 494, in to_response
    return await response_handler(app=app, data=data, request=request)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/litestar/handlers/http_handlers/_utils.py", line 153, in handler
    return response.to_asgi_response(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/litestar/response/template.py", line 130, in to_asgi_response
    body = template.render(**context).encode(self.encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 6, in top-level template code
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "<template>", line 5, in template
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/litestar/template/base.py", line 42, in url_for
    return context["request"].app.route_reverse(route_name, **path_parameters)
           ~~~~~~~^^^^^^^^^^^
  File "/home/geeshta/prog/litestar/bugs/.venv/lib/python3.11/site-packages/jinja2/runtime.py", line 331, in __getitem__
    raise KeyError(key)
KeyError: 'request'
```

### Litestar Version

2.1.1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2461">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2461/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2461/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Have you tried importing the macro `with context`?

So `{% import "macros.html.j2" as render with context %}`

**Comment by geeshta** [comment]
@provinzkraut I have not and it fixed the issue. Thanks!
