### ISSUE TITLE
Bug: binary files can't be uploaded if logging is active without structlog installed

### ISSUE THREAD

**Issue by brakhane** [litestar-org/litestar#2529]
### Description

*This is a pro forma report, I will create a PR that fixes this*

### MCVE

```python
from typing import Annotated

from litestar import Litestar, post
from litestar.datastructures import UploadFile
from litestar.enums import RequestEncodingType
from litestar.logging import LoggingConfig
from litestar.middleware.logging import LoggingMiddlewareConfig
from litestar.params import Body


@post("/")
async def handler(data: Annotated[UploadFile, Body(media_type=RequestEncodingType.MULTI_PART)]) -> str:
    return "foo"

app = Litestar(
        route_handlers=[handler],
        middleware=[LoggingMiddlewareConfig().middleware],
        logging_config=LoggingConfig(),
)
```

### Steps to reproduce

```bash
Now, install litestar *without* structlog and run it:


pip install litestar[standard]
LITESTAR_APP=bug:app litestar run --debug


Posting a binary file that contains an invalid UTF-8 sequence will cause an exception.

```
Traceback (most recent call last):                                                                              
  File "/home/dennis/src/litestar/litestar/middleware/exceptions/middleware.py", line 191, in __call__
    await self.app(scope, receive, send)                                                                        
  File "/home/dennis/src/litestar/litestar/middleware/base.py", line 129, in wrapped_call
    await original__call__(self, scope, receive, send)
  File "/home/dennis/src/litestar/litestar/middleware/logging.py", line 115, in __call__    
    await self.log_request(scope=scope, receive=receive)                                                        
  File "/home/dennis/src/litestar/litestar/middleware/logging.py", line 129, in log_request           
    extracted_data = await self.extract_request_data(request=scope["app"].request_class(scope, receive=receive))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dennis/src/litestar/litestar/middleware/logging.py", line 183, in extract_request_data            
    data[key] = self._serialize_value(serializer, value)                                
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "/home/dennis/src/litestar/litestar/middleware/logging.py", line 164, in _serialize_value
    return value.decode("utf-8") if isinstance(value, bytes) else value                                         
           ^^^^^^^^^^^^^^^^^^^^^                                                                                
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfa in position 134: invalid start byte        
```

The problem is that the body is not parsed when structlog is not installed, and therefore the raw byte sequence will get logged, however, the serialize function assumes it's always valid utf-8.
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

2.2.1 and main

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by peterschutt** [comment]
Thanks!
