### ISSUE TITLE
Bug: Exception in event listener breaks listener

### ISSUE THREAD

**Issue by bnjmn** [litestar-org/litestar#2809]
### Description

In a separate production code base, we encountered what I believe to be an issue/behavior that could be fixed/improved and did not find anything other references of it when searching the issues here. 

Basically, if an exception occurs inside of an event listener you will then see
```log
INFO:     ASGI 'lifespan' protocol appears unsupported.
```
 and the listener stream is closed which then prevents any additional events from being picked up. Any time `request.app.emit` is then called you will get `ClosedResourceError`.

I don't think a single exception inside an event execution should prevent all future events from getting picked up or at least the error should be a little more obvious as to what is going on.

I've created an example repo that recreates the issue consistently.

### URL to code causing the issue

https://github.com/bnjmn/litestar-emit-fail-example

### MCVE

See [full example here](https://github.com/bnjmn/litestar-emit-fail-example/tree/main)
```python
from litestar import Litestar, get, Request
from litestar.events import listener

import logging

logger = logging.getLogger(__name__)

@listener("raise_exception")
async def raise_exception_if_odd(value) -> None:
    """Raise an exception to test Emit error."""
    if value is not None and value % 2 != 0:
        raise ValueError(f"{value} is odd")
    else:
        return "The value is even. No exception raised."

@get("/")
async def index() -> str:
    return "Hello, world!"

@get("/check-value/{value:int}")
async def check_value(request: Request, value: int) -> str:
    try:
        request.app.emit("raise_exception", value)
        return f"Checked {value}: No exception raised."
    except ValueError as e:
        return str(e)

app = Litestar([index, check_value], listeners=[raise_exception_if_odd])
```

### Steps to reproduce

1. Follow the steps outlined in the [README](https://github.com/bnjmn/litestar-emit-fail-example/blob/main/README.md#run-it)
```bash
pipenv install
litestar run -d
```
- Go to http://localhost:8000/check-value/2 to see a successful request
- Go to http://localhost:8000/check-value/3 to see an exception raised in the listener
- Attempt to go to http://localhost:8000/check-value/2 again, but you should get ClosedResourceError

### Litestar Version

Recreated on both 2.3.2 and 2.4.1

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [x] Other (Please specify in the description above)

**Comment by peterschutt** [comment]
Thanks for the excellent reproduction!

**Comment by peterschutt** [comment]
Nicer exception formatting:

```python
Traceback (most recent call last):
  File "/home/peter/PycharmProjects/litestar/litestar/app.py", line 574, in lifespan
    yield
  File "/home/peter/PycharmProjects/litestar/litestar/_asgi/asgi_router.py", line 164, in lifespan
    message = await receive()
  File "/home/peter/.local/share/pdm/venvs/litestar-hello-world-qe1MW6VZ-3.8/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 60, in inner_receive
    message = await receive()
  File "/home/peter/.local/share/pdm/venvs/litestar-hello-world-qe1MW6VZ-3.8/lib/python3.8/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
  File "/home/peter/.pyenv/versions/3.8.18/lib/python3.8/asyncio/queues.py", line 163, in get
    await getter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/home/peter/PycharmProjects/litestar/litestar/_asgi/asgi_router.py", line 164, in lifespan
  |     message = await receive()
  |   File "/home/peter/.pyenv/versions/3.8.18/lib/python3.8/contextlib.py", line 189, in __aexit__
  |     await self.gen.athrow(typ, value, traceback)
  |   File "/home/peter/PycharmProjects/litestar/litestar/app.py", line 574, in lifespan
  |     yield
  |   File "/home/peter/.pyenv/versions/3.8.18/lib/python3.8/contextlib.py", line 679, in __aexit__
  |     raise exc_details[1]
  |   File "/home/peter/.pyenv/versions/3.8.18/lib/python3.8/contextlib.py", line 662, in __aexit__
  |     cb_suppress = await cb(*exc_details)
  |   File "/home/peter/PycharmProjects/litestar/litestar/events/emitter.py", line 116, in __aexit__
  |     await self._exit_stack.__aexit__(exc_type, exc_val, exc_tb)
  |   File "/home/peter/.pyenv/versions/3.8.18/lib/python3.8/contextlib.py", line 679, in __aexit__
  |     raise exc_details[1]
  |   File "/home/peter/.pyenv/versions/3.8.18/lib/python3.8/contextlib.py", line 662, in __aexit__
  |     cb_suppress = await cb(*exc_details)
  |   File "/home/peter/.local/share/pdm/venvs/litestar-hello-world-qe1MW6VZ-3.8/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 664, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/peter/PycharmProjects/litestar/litestar/events/emitter.py", line 88, in _worker
    |     async for item in receive_stream:
    |   File "/home/peter/.local/share/pdm/venvs/litestar-hello-world-qe1MW6VZ-3.8/lib/python3.8/site-packages/anyio/abc/_streams.py", line 35, in __anext__
    |     return await self.receive()
    |   File "/home/peter/.local/share/pdm/venvs/litestar-hello-world-qe1MW6VZ-3.8/lib/python3.8/site-packages/anyio/streams/memory.py", line 105, in receive
    |     await receive_event.wait()
    |   File "/home/peter/.local/share/pdm/venvs/litestar-hello-world-qe1MW6VZ-3.8/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 1621, in wait
    |     await self._event.wait()
    |   File "/home/peter/.pyenv/versions/3.8.18/lib/python3.8/asyncio/locks.py", line 309, in wait
    |     await fut
    | asyncio.exceptions.CancelledError
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Exception Group Traceback (most recent call last):
    |   File "/home/peter/PycharmProjects/litestar/litestar/events/emitter.py", line 95, in _worker
    |     print(exc)
    |   File "/home/peter/.local/share/pdm/venvs/litestar-hello-world-qe1MW6VZ-3.8/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 664, in __aexit__
    |     raise BaseExceptionGroup(
    | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "/home/peter/PycharmProjects/litestar-hello-world/app.py", line 12, in raise_exception_if_odd
      |     raise ValueError(f"{value} is odd")
      | ValueError: 3 is odd
      +------------------------------------
```
