### ISSUE TITLE
Bug: 500: operation_ids must be unique, please ensure the value of 'operation_id' is either not set or unique for GetList

### ISSUE THREAD

**Issue by eandersons** [litestar-org/litestar#2883]
### Description

I was following the [Developing a basic TODO application](https://docs.litestar.dev/2/tutorials/todo-app/index.html) tutorial, and I encountered the error `500: operation_ids must be unique, please ensure the value of 'operation_id' is either not set or unique for GetList` when trying to view automatically generated API documentation for the [final application](https://docs.litestar.dev/2/tutorials/todo-app/3-assembling-the-app.html#final-application) at <http://localhost:8000/schema>.
Application itself is working fine.

For a while I could not figure out why is that (although from the beginning I was suspicious about the two route handlers having the same path `/`), and then I changed `@post("/")` to `@post("/add")`, and the error was gone.

Is this an error in the tutorial, Litestar or somewhere else?
I saw somewhere that combination of method and path should be taken into account for checking the uniqueness of a route, but seems that API documentation generator does not do that.

### URL to code causing the issue

<https://docs.litestar.dev/2/tutorials/todo-app/3-assembling-the-app.html#final-application>

### MCVE

```python
from dataclasses import dataclass

from litestar import Litestar, get, post, put
from litestar.exceptions import NotFoundException


@dataclass
class TodoItem:
    title: str
    done: bool


TODO_LIST: list[TodoItem] = [
    TodoItem(title="Start writing TODO list", done=True),
    TodoItem(title="???", done=False),
    TodoItem(title="Profit", done=False),
]


def get_todo_by_title(todo_name) -> TodoItem:
    for item in TODO_LIST:
        if item.title == todo_name:
            return item

    raise NotFoundException(detail=f"TODO {todo_name!r} not found")


@get("/")
async def get_list(done: bool | None = None) -> list[TodoItem]:
    if done is None:
        return TODO_LIST

    return [item for item in TODO_LIST if item.done == done]


@post("/")
async def add_item(data: TodoItem) -> list[TodoItem]:
    TODO_LIST.append(data)

    return TODO_LIST


@put("/{item_title:str}")
async def update_item(item_title: str, data: TodoItem) -> list[TodoItem]:
    todo_item = get_todo_by_title(item_title)
    todo_item.title = data.title
    todo_item.done = data.done

    return TODO_LIST


app = Litestar([get_list, add_item, update_item], debug=True)
```
### Steps to reproduce

1. Create `app.py` with the content above.
2. Run Litestar server.
3. Go to <http://localhost:8000/schema>.
4. See error.

### Logs

```bash
ERROR - 2023-12-12 07:30:00,612 - litestar - config - exception raised on http connection to route /schema

Traceback (most recent call last):
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/middleware/exceptions/middleware.py", line 191, in __call__
    await self.app(scope, receive, send)
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/routes/http.py", line 81, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/routes/http.py", line 133, in _get_response_for_request
    return await self._call_handler_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/routes/http.py", line 153, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/routes/http.py", line 199, in _get_response_data
    data = route_handler.fn(**parsed_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/openapi/controller.py", line 267, in rapidoc
    return ASGIResponse(body=self.render_rapidoc(request), media_type=MediaType.HTML)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/openapi/controller.py", line 479, in render_rapidoc
    schema = self.get_schema_from_request(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/openapi/controller.py", line 96, in get_schema_from_request
    return request.app.openapi_schema
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/app.py", line 585, in openapi_schema
    return self.plugins.get(OpenAPIPlugin).provide_openapi()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/_openapi/plugin.py", line 48, in provide_openapi
    self._openapi_schema = self._build_openapi_schema()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/_openapi/plugin.py", line 41, in _build_openapi_schema
    openapi.paths = {
                    ^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/_openapi/plugin.py", line 42, in <dictcomp>
    route.path_format or "/": create_path_item_for_route(context, route) for route in self.included_routes
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/_openapi/path_item.py", line 137, in create_path_item_for_route
    return path_item_factory.create_path_item()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/_openapi/path_item.py", line 42, in create_path_item
    operation = self.create_operation_for_handler_method(route_handler, HttpMethod(http_method))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/_openapi/path_item.py", line 60, in create_operation_for_handler_method
    operation_id = self.create_operation_id(route_handler, http_method)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/_openapi/path_item.py", line 107, in create_operation_id
    self.context.add_operation_id(operation_id)
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/_openapi/datastructures.py", line 45, in add_operation_id
    raise ImproperlyConfiguredException(
litestar.exceptions.http_exceptions.ImproperlyConfiguredException: 500: operation_ids must be unique, please ensure the value of 'operation_id' is either not set or unique for GetList
Traceback (most recent call last):
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/middleware/exceptions/middleware.py", line 191, in __call__
    await self.app(scope, receive, send)
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/routes/http.py", line 81, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/routes/http.py", line 133, in _get_response_for_request
    return await self._call_handler_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/routes/http.py", line 153, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/routes/http.py", line 199, in _get_response_data
    data = route_handler.fn(**parsed_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/openapi/controller.py", line 267, in rapidoc
    return ASGIResponse(body=self.render_rapidoc(request), media_type=MediaType.HTML)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/openapi/controller.py", line 479, in render_rapidoc
    schema = self.get_schema_from_request(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/openapi/controller.py", line 96, in get_schema_from_request
    return request.app.openapi_schema
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/app.py", line 585, in openapi_schema
    return self.plugins.get(OpenAPIPlugin).provide_openapi()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/_openapi/plugin.py", line 48, in provide_openapi
    self._openapi_schema = self._build_openapi_schema()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/_openapi/plugin.py", line 41, in _build_openapi_schema
    openapi.paths = {
                    ^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/_openapi/plugin.py", line 42, in <dictcomp>
    route.path_format or "/": create_path_item_for_route(context, route) for route in self.included_routes
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/_openapi/path_item.py", line 137, in create_path_item_for_route
    return path_item_factory.create_path_item()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/_openapi/path_item.py", line 42, in create_path_item
    operation = self.create_operation_for_handler_method(route_handler, HttpMethod(http_method))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/_openapi/path_item.py", line 60, in create_operation_for_handler_method
    operation_id = self.create_operation_id(route_handler, http_method)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/_openapi/path_item.py", line 107, in create_operation_id
    self.context.add_operation_id(operation_id)
  File "/srv/app/venv/lib/python3.11/site-packages/litestar/_openapi/datastructures.py", line 45, in add_operation_id
    raise ImproperlyConfiguredException(
litestar.exceptions.http_exceptions.ImproperlyConfiguredException: 500: operation_ids must be unique, please ensure the value of 'operation_id' is either not set or unique for GetList
INFO:     172.20.0.1:44166 - "GET /schema HTTP/1.1" 500 Internal Server Error
```

### Litestar Version

2.4.3 with Python 3.11

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2883">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2883/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2883/pledge.svg">
</picture>
</a>

**Comment by sinisaos** [comment]
@eandersons This has been fixed [here](https://github.com/litestar-org/litestar/pull/2841) but not yet released. If you try the `main` Litestar branch, everything is fine. Sorry if I'm wrong.

**Comment by peterschutt** [comment]
@sinisaos is correct - this is patched in main but fix is in https://github.com/litestar-org/litestar/pull/2864
