### ISSUE TITLE
Bug: Undesired behavior when `populate_by_name` is set to `True` and an alias is used in a `pydantic.Field`

### ISSUE THREAD

**Issue by Alc-Alc** [litestar-org/litestar#2953]
### Description

When a `pydantic.BaseModel` has `populate_by_name` set to `True` and one of the fields has an alias (in this case `SomeModelAlias.id`with an alias `_id`) the implicit conversion that happens (`correct_route`) does not happen (`probably_buggy_route`). The expected outcome is for both the routes in the example to function identical from a client perspective.

### MCVE
Will try to make it "more MCVE" if I can narrow it down, but I have placed two routes and models that demonstrate the behavior I expect and why the current one is undesired in my opinion.

```python
from typing_extensions import Annotated
from litestar import post
from litestar.dto import DTOConfig, DTOData
from litestar.contrib.pydantic import PydanticDTO
from litestar.testing import create_test_client
from pydantic import BaseModel, ConfigDict, Field

class SomeModelNoAlias(BaseModel):
    id: str
    name: str

class SomeModelAlias(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    id: str = Field(alias="_id")
    name: str

@post(
    "correct_route",
    dto=PydanticDTO[Annotated[SomeModelNoAlias, DTOConfig({"id"})]],
    return_dto=PydanticDTO[SomeModelNoAlias],
)
async def correct_route(data: DTOData[SomeModelNoAlias]) -> SomeModelNoAlias:
    # serialization works, implicitly converted to ``SomeModelNoAlias``
    return {"id": "some id", **data.as_builtins()}

@post(
    "probably_buggy_route",
    dto=PydanticDTO[Annotated[SomeModelAlias, DTOConfig({"id"})]],
    return_dto=PydanticDTO[SomeModelAlias],
)
async def probably_buggy_route(data: DTOData[SomeModelAlias]) -> SomeModelAlias:
    generated_data = {"_id": "some id", **data.as_builtins()}

    # this is the ser/de behavior I expect
    # notice that ``_id`` in ``generated_data`` is a valid name to be passed
    assert SomeModelAlias.model_validate(generated_data).model_dump() == expected_data

    # serialization fails, implicit conversion to ``SomeModelAlias`` fails
    return generated_data

with create_test_client([correct_route, probably_buggy_route]) as client:
    input_data = {"name": "some name"}
    expected_data = {"id": "some id", "name": "some name"}

    response = client.post("correct_route", json=input_data)
    assert response.status_code == 201
    assert response.json() == expected_data

    response = client.post("probably_buggy_route", json=input_data)
    assert response.status_code == 201, "Current: 500, Expected: 201"
    assert response.json() == expected_data, "Should return the same as /correct_route"
```

### Steps to reproduce

```bash
1. Save as `some_python_file.py`
2. Run `python some_python_file.py`
3. The assert for `/probably_buggy_route` fails
*gru from despicable me looking back in confusion*
4. The assert for `/probably_buggy_route` fails
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Logs

```bash
ERROR - ,-557760006 - litestar - middleware - exception raised on http connection to route /probably_buggy_route

Traceback (most recent call last):
  File "litestar/litestar/middleware/exceptions/middleware.py", line 192, in __call__
    await self.app(scope, receive, send)
  File "litestar/litestar/routes/http.py", line 82, in handle
    response = await self._get_response_for_request(
  File "litestar/litestar/routes/http.py", line 134, in _get_response_for_request
    return await self._call_handler_function(
  File "litestar/litestar/routes/http.py", line 158, in _call_handler_function
    response: ASGIApp = await route_handler.to_response(app=scope["app"], data=response_data, request=request)
  File "litestar/litestar/handlers/http_handlers/base.py", line 526, in to_response
    data = return_dto_type(request).data_to_encodable_type(data)
  File "litestar/litestar/dto/base_dto.py", line 101, in data_to_encodable_type
    return backend.encode_data(data)
  File "litestar/litestar/dto/_backend.py", line 351, in encode_data
    _transfer_data(
  File "litestar/litestar/dto/_backend.py", line 600, in _transfer_data
    return _transfer_instance_data(
  File "litestar/litestar/dto/_backend.py", line 640, in _transfer_instance_data
    source_instance[field_definition.name]
KeyError: 'id'
Traceback (most recent call last):
  File "litestar/litestar/middleware/exceptions/middleware.py", line 192, in __call__
    await self.app(scope, receive, send)
  File "litestar/litestar/routes/http.py", line 82, in handle
    response = await self._get_response_for_request(
  File "litestar/litestar/routes/http.py", line 134, in _get_response_for_request
    return await self._call_handler_function(
  File "litestar/litestar/routes/http.py", line 158, in _call_handler_function
    response: ASGIApp = await route_handler.to_response(app=scope["app"], data=response_data, request=request)
  File "litestar/litestar/handlers/http_handlers/base.py", line 526, in to_response
    data = return_dto_type(request).data_to_encodable_type(data)
  File "litestar/litestar/dto/base_dto.py", line 101, in data_to_encodable_type
    return backend.encode_data(data)
  File "litestar/litestar/dto/_backend.py", line 351, in encode_data
    _transfer_data(
  File "litestar/litestar/dto/_backend.py", line 600, in _transfer_data
    return _transfer_instance_data(
  File "litestar/litestar/dto/_backend.py", line 640, in _transfer_instance_data
    source_instance[field_definition.name]
KeyError: 'id'
Traceback (most recent call last):
  File "litestar/app.py", line 50, in <module>
    assert response.status_code == 201, "Current: 500, Expected: 201"
AssertionError: Current: 500, Expected: 201
```

### Litestar Version

804f0151fc9b03e81f6cb6cbb38a9dfd395ead79 (main as of issue creation)

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by Alc-Alc** [comment]
I tried to replicate the same using `msgspec.Struct`, while it has an alias feature using `field(..., name='alias here')` it does not seem to have the concept of "populate using alias" that pydantic has

**Comment by cofin** [comment]
@Alc-Alc The latest release of msgspec ma resolve this issue.

**Comment by cofin** [comment]
Closing this issue as it's a misunderstanding of functionality.  The return type is a `dict` in the examples above instead of a `PydanticModel`.  You should still return a Pydantic model from your function even when using a DTO.

For instance, this fails the last assertion only:
```python
from typing import Annotated

from litestar import post
from litestar.contrib.pydantic import PydanticDTO
from litestar.dto import DTOConfig, DTOData
from litestar.testing import create_test_client
from pydantic import BaseModel, ConfigDict, Field


class SomeModelNoAlias(BaseModel):
    id: str
    name: str


class SomeModelAlias(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    id: str = Field(alias="_id")
    name: str


@post(
    "correct_route",
    dto=PydanticDTO[
        Annotated[
            SomeModelNoAlias,
            DTOConfig({"id"}, experimental_codegen_backend=True, underscore_fields_private=False),
        ]
    ],
    return_dto=PydanticDTO[SomeModelNoAlias],
)
async def correct_route(data: DTOData[SomeModelNoAlias]) -> SomeModelNoAlias:
    # serialization works, implicitly converted to ``SomeModelNoAlias``
    return {"id": "some id", **data.as_builtins()}


@post(
    "probably_buggy_route",
    dto=PydanticDTO[Annotated[SomeModelAlias, DTOConfig({"id"})]],
    return_dto=None,
)
async def probably_buggy_route(data: DTOData[SomeModelAlias]) -> SomeModelAlias:
    generated_data = {"_id": "some id", **data.as_builtins()}

    # this is the ser/de behavior I expect
    # notice that ``_id`` in ``generated_data`` is a valid name to be passed
    assert SomeModelAlias.model_validate(generated_data).model_dump() == expected_data

    # serialization fails, implicit conversion to ``SomeModelAlias`` fails
    return generated_data


with create_test_client([correct_route, probably_buggy_route]) as client:
    input_data = {"name": "some name"}
    expected_data = {"id": "some id", "name": "some name"}

    response = client.post("correct_route", json=input_data)
    assert response.status_code == 201
    assert response.json() == expected_data

    response = client.post("probably_buggy_route", json=input_data)
    assert response.status_code == 201, "Current: 500, Expected: 201"
    assert response.json() == expected_data, "Should return the same as /correct_route"
   ```

and this works out of the box:

```python
from typing import Annotated

from litestar import post
from litestar.contrib.pydantic import PydanticDTO
from litestar.dto import DTOConfig, DTOData
from litestar.testing import create_test_client
from pydantic import BaseModel, ConfigDict, Field


class SomeModelNoAlias(BaseModel):
    id: str
    name: str


class SomeModelAlias(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    id: str = Field(alias="_id")
    name: str


@post(
    "correct_route",
    dto=PydanticDTO[
        Annotated[
            SomeModelNoAlias,
            DTOConfig({"id"}, experimental_codegen_backend=True, underscore_fields_private=False),
        ]
    ],
    return_dto=PydanticDTO[SomeModelNoAlias],
)
async def correct_route(data: DTOData[SomeModelNoAlias]) -> SomeModelNoAlias:
    # serialization works, implicitly converted to ``SomeModelNoAlias``
    return {"id": "some id", **data.as_builtins()}


@post(
    "probably_buggy_route",
    dto=PydanticDTO[Annotated[SomeModelAlias, DTOConfig({"id"})]],
    return_dto=None,
)
async def probably_buggy_route(data: DTOData[SomeModelAlias]) -> SomeModelAlias:
    generated_data = {"_id": "some id", **data.as_builtins()}

    # this is the ser/de behavior I expect
    # notice that ``_id`` in ``generated_data`` is a valid name to be passed
    assert SomeModelAlias.model_validate(generated_data).model_dump() == expected_data

    # serialization fails, implicit conversion to ``SomeModelAlias`` fails
    return SomeModelAlias.model_validate(generated_data)


with create_test_client([correct_route, probably_buggy_route]) as client:
    input_data = {"name": "some name"}
    expected_data = {"id": "some id", "name": "some name"}

    response = client.post("correct_route", json=input_data)
    assert response.status_code == 201
    assert response.json() == expected_data

    response = client.post("probably_buggy_route", json=input_data)
    assert response.status_code == 201, "Current: 500, Expected: 201"
    assert response.json() == expected_data, "Should return the same as /correct_route"
```

**Comment by cofin** [comment]
Closing
