### ISSUE TITLE
Bug: `exceptiongroup` backport is missing on Python 3.10

### ISSUE THREAD

**Issue by mtvx** [litestar-org/litestar#3029]
### Description

Code expects `exceptiongroup` backport to be installed in https://github.com/litestar-org/litestar/blob/6e4e530445eadbc1fd2f65bebca3bc68cf12f29a/litestar/utils/helpers.py#L101

However, it's only declared for _dev_ dependencies in https://github.com/litestar-org/litestar/blob/6e4e530445eadbc1fd2f65bebca3bc68cf12f29a/pyproject.toml#L109 so after `litestar` install it won't be found and one has to manually require it now.

Running Python 3.10.

### Logs

Full stacktrace (failure on launch):

```

Traceback (most recent call last):
  File "/home/api/.local/lib/python3.10/site-packages/litestar/utils/helpers.py", line 99, in get_exception_group
    return cast("type[BaseException]", ExceptionGroup)  # type:ignore[name-defined]
NameError: name 'ExceptionGroup' is not defined. Did you mean: '_ExceptionGroup'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/myproject/api/myproject/cloud_management/new_app.py", line 4, in <module>
    from litestar import Litestar
  File "/home/api/.local/lib/python3.10/site-packages/litestar/__init__.py", line 1, in <module>
    from litestar.app import Litestar
  File "/home/api/.local/lib/python3.10/site-packages/litestar/app.py", line 20, in <module>
    from litestar._openapi.plugin import OpenAPIPlugin
  File "/home/api/.local/lib/python3.10/site-packages/litestar/_openapi/plugin.py", line 10, in <module>
    from litestar.routes import HTTPRoute
  File "/home/api/.local/lib/python3.10/site-packages/litestar/routes/__init__.py", line 1, in <module>
    from .asgi import ASGIRoute
  File "/home/api/.local/lib/python3.10/site-packages/litestar/routes/asgi.py", line 7, in <module>
    from litestar.routes.base import BaseRoute
  File "/home/api/.local/lib/python3.10/site-packages/litestar/routes/base.py", line 13, in <module>
    from litestar._kwargs import KwargsModel
  File "/home/api/.local/lib/python3.10/site-packages/litestar/_kwargs/__init__.py", line 1, in <module>
    from .kwargs_model import KwargsModel
  File "/home/api/.local/lib/python3.10/site-packages/litestar/_kwargs/kwargs_model.py", line 49, in <module>
    _ExceptionGroup = get_exception_group()
  File "/home/api/.local/lib/python3.10/site-packages/litestar/utils/helpers.py", line 101, in get_exception_group
    from exceptiongroup import ExceptionGroup as _ExceptionGroup  # pyright: ignore
ModuleNotFoundError: No module named 'exceptiongroup'
```

### Litestar Version

2.5.1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3029">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3029/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3029/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
Thanks, this was originally a testing utility that was moved into the main lib at some point and this would have been missed. PR welcome!
