### ISSUE TITLE
Bug: Logging middleware with structlog causes application to return HTTP 500 when request body is malformed

### ISSUE THREAD

**Issue by zoopp** [litestar-org/litestar#3063]
### Description

It looks to me that the logging middleware is attempting to parse the body of the incoming requests and if the parsing fails this results in an HTTP 500 Internal Error instead of an HTTP 400 Bad Request. If I don't use the logging middleware, the behavior is what I would normally expect to happen.

I've tested this with standard logging and structlog (structlog being what I use in my project) and the behavior is the same.

### MCVE

```python
from typing import Any

from litestar import Litestar, post
from litestar.logging.config import LoggingConfig, StructLoggingConfig
from litestar.middleware.logging import LoggingMiddlewareConfig


@post("/")
async def hello_world(data: dict[str, Any]) -> dict[str, Any]:
    """Route Handler that outputs hello world."""
    return data


app = Litestar(
    route_handlers=[hello_world],
    # logging_config=LoggingConfig(log_exceptions="always"),  # Also happens with standard logging
    logging_config=StructLoggingConfig(log_exceptions="always"),
    middleware=[LoggingMiddlewareConfig().middleware],
)
```

### Steps to reproduce

```bash
1. Run example, e.g.: `litestar --app bug:app run`
2. Post invalid json: `curl --header "Content-Type: application/json" --request POST --data '{"a": "b",}' http://localhost:8000`
3. Examine the logs.
```

### Logs

```bash
!!! I'm using the standard logging version output as it formats the exception in a readable manner
!!! but the outcome is essentially the same regardless if using structlog or standard logging.

┌─┤10:26:41│mihai@mobilews:~/bug
└──────────╼ litestar --app bug:app run
Using Litestar app from env: 'bug:app'
Starting server process ───────────────────────────────────────────────────────────────────────────────────────────────────────
┌──────────────────────────────┬──────────────────────┐
│ Litestar version             │ 2.5.4                │
│ Debug mode                   │ Disabled             │
│ Python Debugger on exception │ Disabled             │
│ CORS                         │ Disabled             │
│ CSRF                         │ Disabled             │
│ OpenAPI                      │ Enabled path=/schema │
│ Compression                  │ Disabled             │
│ Middlewares                  │ LoggingMiddleware    │
└──────────────────────────────┴──────────────────────┘
INFO:     Started server process [110144]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:35020 - "POST / HTTP/1.1" 500 Internal Server Error
ERROR - 2024-02-02 10:26:45,152 - litestar - config - exception raised on http connection to route /

Traceback (most recent call last):
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/serialization/msgspec_hooks.py", line 186, in decode_json
    return _msgspec_json_decoder.decode(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
msgspec.DecodeError: JSON is malformed: trailing comma in object (byte 10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/middleware/exceptions/middleware.py", line 192, in __call__
    await self.app(scope, receive, send)
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/middleware/base.py", line 129, in wrapped_call
    await original__call__(self, scope, receive, send)  # pyright: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/middleware/logging.py", line 112, in __call__
    await self.log_request(scope=scope, receive=receive)
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/middleware/logging.py", line 126, in log_request
    extracted_data = await self.extract_request_data(request=scope["app"].request_class(scope, receive))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/middleware/logging.py", line 179, in extract_request_data
    value = await value
            ^^^^^^^^^^^
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/data_extractors.py", line 277, in extract_body
    return await request.json()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/connection/request.py", line 134, in json
    self._json = self._connection_state.json = decode_json(
                                               ^^^^^^^^^^^^
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/serialization/msgspec_hooks.py", line 191, in decode_json
    raise SerializationException(str(msgspec_error)) from msgspec_error
litestar.exceptions.base_exceptions.SerializationException: JSON is malformed: trailing comma in object (byte 10)
Traceback (most recent call last):
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/serialization/msgspec_hooks.py", line 186, in decode_json
    return _msgspec_json_decoder.decode(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
msgspec.DecodeError: JSON is malformed: trailing comma in object (byte 10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/middleware/exceptions/middleware.py", line 192, in __call__
    await self.app(scope, receive, send)
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/middleware/base.py", line 129, in wrapped_call
    await original__call__(self, scope, receive, send)  # pyright: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/middleware/logging.py", line 112, in __call__
    await self.log_request(scope=scope, receive=receive)
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/middleware/logging.py", line 126, in log_request
    extracted_data = await self.extract_request_data(request=scope["app"].request_class(scope, receive))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/middleware/logging.py", line 179, in extract_request_data
    value = await value
            ^^^^^^^^^^^
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/data_extractors.py", line 277, in extract_body
    return await request.json()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/connection/request.py", line 134, in json
    self._json = self._connection_state.json = decode_json(
                                               ^^^^^^^^^^^^
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/serialization/msgspec_hooks.py", line 191, in decode_json
    raise SerializationException(str(msgspec_error)) from msgspec_error
litestar.exceptions.base_exceptions.SerializationException: JSON is malformed: trailing comma in object (byte 10)
```

### Litestar Version

litestar[standard]==2.5.4
structlog==24.1.0

### Platform

- [x] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3063">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3063/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3063/pledge.svg">
</picture>
</a>

**Comment by cofin** [comment]
I think this has been resolved in the development branch.  @zoopp are you able to give that branch a try to confirm if the problem remains?

**Comment by zoopp** [comment]
@cofin I gave it a try now but the issue is still reproducible with the MCVE above:

```
(litestar)
┌─┤10:11:07│mihai@mobilews:~/bug
└──────────╼ litestar --app bug:app run --reload
Using Litestar app from env: 'bug:app'
Starting server process ───────────────────────────────────────────────────────────────────────────────────────────────────────
┌──────────────────────────────┬──────────────────────┐
│ Litestar version             │ 2.6.0                │
│ Debug mode                   │ Disabled             │
│ Python Debugger on exception │ Disabled             │
│ CORS                         │ Disabled             │
│ CSRF                         │ Disabled             │
│ OpenAPI                      │ Enabled path=/schema │
│ Compression                  │ Disabled             │
│ Middlewares                  │ LoggingMiddleware    │
└──────────────────────────────┴──────────────────────┘
INFO:     Will watch for changes in these directories: ['/home/mihai/bug']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [150319] using WatchFiles
INFO:     Started server process [150321]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:58246 - "POST / HTTP/1.1" 500 Internal Server Error
ERROR - 2024-02-05 10:11:12,310 - litestar - config - exception raised on http connection to route /

Traceback (most recent call last):
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/serialization/msgspec_hooks.py", line 186, in decode_json
    return _msgspec_json_decoder.decode(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
msgspec.DecodeError: JSON is malformed: trailing comma in object (byte 10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/middleware/exceptions/middleware.py", line 192, in __call__
    await self.app(scope, receive, send)
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/middleware/base.py", line 129, in wrapped_call
    await original__call__(self, scope, receive, send)  # pyright: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/middleware/logging.py", line 112, in __call__
    await self.log_request(scope=scope, receive=receive)
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/middleware/logging.py", line 126, in log_request
    extracted_data = await self.extract_request_data(request=scope["app"].request_class(scope, receive))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/middleware/logging.py", line 179, in extract_request_data
    value = await value
            ^^^^^^^^^^^
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/data_extractors.py", line 277, in extract_body
    return await request.json()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/connection/request.py", line 134, in json
    self._json = self._connection_state.json = decode_json(
                                               ^^^^^^^^^^^^
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/serialization/msgspec_hooks.py", line 191, in decode_json
    raise SerializationException(str(msgspec_error)) from msgspec_error
litestar.exceptions.base_exceptions.SerializationException: JSON is malformed: trailing comma in object (byte 10)
Traceback (most recent call last):
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/serialization/msgspec_hooks.py", line 186, in decode_json
    return _msgspec_json_decoder.decode(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
msgspec.DecodeError: JSON is malformed: trailing comma in object (byte 10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/middleware/exceptions/middleware.py", line 192, in __call__
    await self.app(scope, receive, send)
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/middleware/base.py", line 129, in wrapped_call
    await original__call__(self, scope, receive, send)  # pyright: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/middleware/logging.py", line 112, in __call__
    await self.log_request(scope=scope, receive=receive)
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/middleware/logging.py", line 126, in log_request
    extracted_data = await self.extract_request_data(request=scope["app"].request_class(scope, receive))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/middleware/logging.py", line 179, in extract_request_data
    value = await value
            ^^^^^^^^^^^
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/data_extractors.py", line 277, in extract_body
    return await request.json()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/connection/request.py", line 134, in json
    self._json = self._connection_state.json = decode_json(
                                               ^^^^^^^^^^^^
  File "/home/mihai/.virtualenvs/litestar/lib/python3.11/site-packages/litestar/serialization/msgspec_hooks.py", line 191, in decode_json
    raise SerializationException(str(msgspec_error)) from msgspec_error
litestar.exceptions.base_exceptions.SerializationException: JSON is malformed: trailing comma in object (byte 10)
```
