### ISSUE TITLE
Bug: can't upload multiple files where `data: Optional[List[UploadFile]]`

### ISSUE THREAD

**Issue by peterschutt** [litestar-org/litestar#3409]
### Description

The following test fails for the 2 files case.

### MCVE

```python
@pytest.mark.parametrize("file_count", (0, 1, 2))
def test_upload_multiple_files_optional(file_count: int) -> None:
    @post("/")
    async def handler(data: Optional[List[UploadFile]] = Body(media_type=RequestEncodingType.MULTI_PART)) -> None:
        if data is None:
            return

        assert len(data) == file_count

        for file in data:
            assert await file.read() == b"1"

    with create_test_client([handler], openapi_config=None) as client:
        files_to_upload = [("file", b"1") for _ in range(file_count)]
        response = client.post("/", files=files_to_upload or None)

        assert response.status_code == HTTP_201_CREATED
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Logs

```bash
Traceback (most recent call last):
  File "/home/peter/PycharmProjects/litestar/litestar/_signature/model.py", line 94, in _deserializer
    return default_deserializer(target_type, value)
  File "/home/peter/PycharmProjects/litestar/litestar/serialization/msgspec_hooks.py", line 127, in default_deserializer
    raise TypeError(f"Unsupported type: {type(value)!r}")
TypeError: Unsupported type: <class 'list'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/peter/PycharmProjects/litestar/litestar/_signature/model.py", line 194, in parse_values_from_connection_kwargs
    return convert(kwargs, cls, strict=False, dec_hook=deserializer, str_keys=True).to_dict()
msgspec.ValidationError: Unsupported type: <class 'list'> - at `$.data[0]`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/peter/PycharmProjects/litestar/litestar/middleware/exceptions/middleware.py", line 216, in __call__
    await self.app(scope, receive, send)
  File "/home/peter/PycharmProjects/litestar/litestar/routes/http.py", line 82, in handle
    response = await self._get_response_for_request(
  File "/home/peter/PycharmProjects/litestar/litestar/routes/http.py", line 134, in _get_response_for_request
    return await self._call_handler_function(
  File "/home/peter/PycharmProjects/litestar/litestar/routes/http.py", line 154, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
  File "/home/peter/PycharmProjects/litestar/litestar/routes/http.py", line 193, in _get_response_data
    parsed_kwargs = route_handler.signature_model.parse_values_from_connection_kwargs(
  File "/home/peter/PycharmProjects/litestar/litestar/_signature/model.py", line 207, in parse_values_from_connection_kwargs
    raise cls._create_exception(messages=messages, connection=connection) from e
litestar.exceptions.http_exceptions.ValidationException: 400: Validation failed for POST /
Traceback (most recent call last):
  File "/home/peter/PycharmProjects/litestar/litestar/_signature/model.py", line 94, in _deserializer
    return default_deserializer(target_type, value)
  File "/home/peter/PycharmProjects/litestar/litestar/serialization/msgspec_hooks.py", line 127, in default_deserializer
    raise TypeError(f"Unsupported type: {type(value)!r}")
TypeError: Unsupported type: <class 'list'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/peter/PycharmProjects/litestar/litestar/_signature/model.py", line 194, in parse_values_from_connection_kwargs
    return convert(kwargs, cls, strict=False, dec_hook=deserializer, str_keys=True).to_dict()
msgspec.ValidationError: Unsupported type: <class 'list'> - at `$.data[0]`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/peter/PycharmProjects/litestar/litestar/middleware/exceptions/middleware.py", line 216, in __call__
    await self.app(scope, receive, send)
  File "/home/peter/PycharmProjects/litestar/litestar/routes/http.py", line 82, in handle
    response = await self._get_response_for_request(
  File "/home/peter/PycharmProjects/litestar/litestar/routes/http.py", line 134, in _get_response_for_request
    return await self._call_handler_function(
  File "/home/peter/PycharmProjects/litestar/litestar/routes/http.py", line 154, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
  File "/home/peter/PycharmProjects/litestar/litestar/routes/http.py", line 193, in _get_response_data
    parsed_kwargs = route_handler.signature_model.parse_values_from_connection_kwargs(
  File "/home/peter/PycharmProjects/litestar/litestar/_signature/model.py", line 207, in parse_values_from_connection_kwargs
    raise cls._create_exception(messages=messages, connection=connection) from e
litestar.exceptions.http_exceptions.ValidationException: 400: Validation failed for POST /
```

### Litestar Version

main

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3409">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3409/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3409/pledge.svg">
</picture>
</a>

**Comment by euri10** [comment]
closed by https://github.com/litestar-org/litestar/pull/3408
