### ISSUE TITLE
Bug: Can't convert sqlalchemy model to pydantic model which is inherited from BaseModel

### ISSUE THREAD

**Issue by monok8i** [litestar-org/litestar#3465]
### Description

**I tried to convert the sqlalchemy model to pydantic BaseModel but I get an error**:

using the `pydantic.type_adapter.TypeAdapter`:
```py
ValidationError: 1 validation error for list[User]
  Input should be a valid list [type=list_type,
input_value=<app.database.models.user...t at 0x000002DCABD17710>,
input_type=User]
```

using the `to_schema` method of the `advanced_alchemy.service.SQLAlchemyAsyncRepositoryService` class:
```py
ValidationError: 1 validation error for list[User]
0
  Input should be a valid dictionary or instance of User [type=model_type,
input_value=<app.database.models.user...t at 0x0000018BE6647990>,
input_type=User]
```

### URL to code causing the issue

https://github.com/monok8i/backend-microservice-structure/blob/main/backend/users-service/app/domain/users/services.py

### MCVE

My Pydantic model:
```python
class UserBase(BaseModel):
    email: Optional[EmailStr] = None
    is_active: Optional[bool] = True
    is_superuser: bool = False
    is_activated: bool = False

class User(UserBase):
    id: int
```

My SQLAlchemy Model:
```py
class Base(AsyncAttrs, DeclarativeBase):
    __table_args__ = {"extend_existing": True}

    @declared_attr.directive
    def __tablename__(cls) -> str:
        return f"{cls.__name__.lower()}s"

    @declared_attr
    def id(cls) -> Mapped[int]:
        return mapped_column(Integer, primary_key=True, index=True)

    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), server_default=func.now()
    )

    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), server_default=func.now(), server_onupdate=func.now()
    )

class User(Base):
    email: Mapped[str] = mapped_column(String, unique=True)
    hashed_password: Mapped[str] = mapped_column(String)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    is_superuser: Mapped[bool] = mapped_column(Boolean, default=False)
    is_activated: Mapped[bool] = mapped_column(Boolean, default=False)
```

The first attempt to convert the sqlalchemy model using `pydantic.type_adapter.TypeAdapter` in the same way as in the inherited `to_schema` method but without `from_attributes` parameter: **(ValidationError)**
```py
from app.domain.users.schemas import User as PydanticUser

class UserService(SQLAlchemyAsyncRepositoryService[User]):
    repository_type: SQLAlchemyAsyncRepository[User] = UserRepository

    def __init__(
        self,
        session: AsyncSession | async_scoped_session[AsyncSession],
        **repo_kwargs: Any,
    ) -> None:
        self.repository = self.repository_type(
            session=session,
            **repo_kwargs,
        )
        self.model = self.repository.model_type

        super().__init__(
            session, statement, auto_expunge, auto_refresh, auto_commit, **repo_kwargs
        )

    async def get_users(self) -> OffsetPagination[PydanticUser]:
        results, count = await self.list_and_count()
        results = [
            TypeAdapter(PydanticUser).validate_python(user) for user in results
        ]
        return self.to_schema(data=results, total=count)
```

The second attempt to convert the sqlalchemy model using the inherited `to_schema` method with no other parameters:  **(ValidationError)**
```py
    async def get_users(self) -> OffsetPagination[PydanticUser]:
        results, count = await self.list_and_count()
        return self.to_schema(data=results, total=count, schema_type=PydanticUser)
```

The attempts to convert a database model in Pydantic but using the `model_validate` method of the `BaseModel` class and `TypeAdapter` with parameter `from_attributes`: 
```py
# first
    async def get_users(self) -> OffsetPagination[PydanticUser]:
        results, count = await self.list_and_count()
        results = [PydanticUser.model_validate(user, from_attributes=True) for user in results]
        return self.to_schema(data=results, total=count)
```
```py
# second
    async def get_users(self) -> OffsetPagination[PydanticUser]:
        results, count = await self.list_and_count()
        results = TypeAdapter(list[PydanticUser]).validate_python([user for user in results], from_attributes=True)
        return self.to_schema(data=results, total=count, schema_type=PydanticUser)
```
```py
# third
    async def get_users(self) -> OffsetPagination[PydanticUser]:
        results, count = await self.list_and_count()
        results = [TypeAdapter(PydanticUser).validate_python(user, from_attributes=True) for user in results]
        return self.to_schema(data=results, total=count, schema_type=PydanticUser)
```
**And already this time everything works correctly, I get my result:**
```json
{
  "items": [
    {
      "email": "admin@admin.admin",
      "is_active": true,
      "is_superuser": true,
      "is_activated": true,
      "id": 1
    }
  ],
  "limit": 1,
  "offset": 0,
  "total": 1
}
```

### Logs

```bash
2024-05-03T16:33:59.571379Z [info     ] HTTP Request                   method=GET path=/api/users path_params={} query={}
INFO - 2024-05-03 18:33:59,817 - sqlalchemy.engine.Engine - base - select pg_catalog.version()
INFO - 2024-05-03 18:33:59,818 - sqlalchemy.engine.Engine - base - [raw sql] ()
INFO - 2024-05-03 18:33:59,821 - sqlalchemy.engine.Engine - base - select current_schema()
INFO - 2024-05-03 18:33:59,821 - sqlalchemy.engine.Engine - base - [raw sql] ()
INFO - 2024-05-03 18:33:59,823 - sqlalchemy.engine.Engine - base - show standard_conforming_strings
INFO - 2024-05-03 18:33:59,823 - sqlalchemy.engine.Engine - base - [raw sql] ()
INFO - 2024-05-03 18:33:59,825 - sqlalchemy.engine.Engine - base - BEGIN (implicit)
INFO - 2024-05-03 18:33:59,829 - sqlalchemy.engine.Engine - base - SELECT users.email, users.hashed_password, users.is_active, users.is_superuser, users.is_activated, users.created_at, users.updated_at, users.id, count(users.id) OVER () AS anon_1
FROM users
INFO - 2024-05-03 18:33:59,830 - sqlalchemy.engine.Engine - base - [generated in 0.00030s] ()
2024-05-03T16:33:59.855384Z [error    ] Uncaught Exception             connection_type=http path=/api/users traceback=  File "C:\Users\Swift\AppData\Local\pypoetry\Cache\virtualenvs\litestar-users-service-E9vRFPaJ-py3.11\Lib\site-packages\advanced_alchemy\service\_async.py", line 297, in to_schema
    return to_schema(data=data, total=total, filters=filters, schema_type=schema_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Swift\AppData\Local\pypoetry\Cache\virtualenvs\litestar-users-service-E9vRFPaJ-py3.11\Lib\site-packages\advanced_alchemy\service\_converters.py", line 148, in to_schema
    items=TypeAdapter(List[schema_type]).validate_python(data),  # type: ignore[valid-type]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Swift\AppData\Local\pypoetry\Cache\virtualenvs\litestar-users-service-E9vRFPaJ-py3.11\Lib\site-packages\pydantic\type_adapter.py", line 260, in validate_python
    return self.validator.validate_python(object, strict=strict, from_attributes=from_attributes, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for list[User]
0
  Input should be a valid dictionary or instance of User [type=model_type, input_value=<app.database.models.user...t at 0x0000018BE6647990>, input_type=User]
    For further information visit https://errors.pydantic.dev/2.7/v/model_type

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ C:\Users\Swift\AppData\Local\pypoetry\Cache\virtualenvs\litestar-users-servi │
│ ce-E9vRFPaJ-py3.11\Lib\site-packages\litestar\middleware\exceptions\middlewa │
│ re.py:219 in __call__                                                        │
│                                                                              │
│   216 │   │   │   None                                                       │
│   217 │   │   """                                                            │
│   218 │   │   try:                                                           │
│ ❱ 219 │   │   │   await self.app(scope, receive, send)                       │
│   220 │   │   except Exception as e:  # noqa: BLE001                         │
│   221 │   │   │   litestar_app = scope["app"]                                │
│   222                                                                        │
│                                                                              │
│ C:\Users\Swift\AppData\Local\pypoetry\Cache\virtualenvs\litestar-users-servi │
│ ce-E9vRFPaJ-py3.11\Lib\site-packages\litestar\routes\http.py:82 in handle    │
│                                                                              │
│    79 │   │   if route_handler.resolve_guards():                             │
│    80 │   │   │   await route_handler.authorize_connection(connection=reques │
│    81 │   │                                                                  │
│ ❱  82 │   │   response = await self._get_response_for_request(               │
│    83 │   │   │   scope=scope, request=request, route_handler=route_handler, │
│    84 │   │   )                                                              │
│    85                                                                        │
│                                                                              │
│                           ... 6 frames hidden ...                            │
│                                                                              │
│ C:\Users\Swift\AppData\Local\pypoetry\Cache\virtualenvs\litestar-users-servi │
│ ce-E9vRFPaJ-py3.11\Lib\site-packages\advanced_alchemy\service\_converters.py │
│ :148 in to_schema                                                            │
│                                                                              │
│   145 │   │   total = total if total else len(data)                          │
│   146 │   │   limit_offset = limit_offset if limit_offset is not None else L │
│   147 │   │   return OffsetPagination[schema_type](  # type: ignore[valid-ty │
│ ❱ 148 │   │   │   items=TypeAdapter(List[schema_type]).validate_python(data) │
│   149 │   │   │   limit=limit_offset.limit,                                  │
│   150 │   │   │   offset=limit_offset.offset,                                │
│   151 │   │   │   total=total,                                               │
│                                                                              │
│ C:\Users\Swift\AppData\Local\pypoetry\Cache\virtualenvs\litestar-users-servi │
│ ce-E9vRFPaJ-py3.11\Lib\site-packages\pydantic\type_adapter.py:260 in         │
│ validate_python                                                              │
│                                                                              │
│   257 │   │   Returns:                                                       │
│   258 │   │   │   The validated object.                                      │
│   259 │   │   """                                                            │
│ ❱ 260 │   │   return self.validator.validate_python(object, strict=strict, f │
│   261 │                                                                      │
│   262 │   def validate_json(                                                 │
│   263 │   │   self, data: str | bytes, /, *, strict: bool | None = None, con │
ValidationError: 1 validation error for list[User]
0
  Input should be a valid dictionary or instance of User [type=model_type,
input_value=<app.database.models.user...t at 0x0000018BE6647990>,
input_type=User]
    For further information visit https://errors.pydantic.dev/2.7/v/model_type
```

### Litestar Version

2.8.2

### Platform

- [ ] Linux
- [ ] Mac
- [X] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3465">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3465/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3465/pledge.svg">
</picture>
</a>

**Comment by monok8i** [comment]
**I solved my problem and the solution can be divided into two options:**

- Manually convert the sqlalchemy model to pydantic using the model inherited from BaseModel and its model_validate method
```python
    async def get_users(self) -> OffsetPagination[PydanticUser]:
        results, count = await self.list_and_count()
        results = [PydanticUser.model_validate(user, from_attributes=True) for user in results]
        return self.to_schema(data=results, total=count, schema_type=PydanticUser)
```

- Manually convert sqlalchemy model to pydantic using TypaAdapter and its validate_python method
```python
    async def get_users(self) -> OffsetPagination[PydanticUser]:
        results, count = await self.list_and_count()
        # first option
        results = TypeAdapter(list[PydanticUser]).validate_python(
            results, from_attributes=True
        )
        # second option
        # results = [TypeAdapter(PydanticUser).validate_python(user, from_attributes=True) for user in results]
        return self.to_schema(data=results, total=count, schema_type=PydanticUser)
```

Important: It is necessary to specify the parameter `from_attributes=True' in the validation methods so that our DTO directly extracts data from the attributes and tries to substitute them

Alternatively, you can add the model_config attribute to your base model as follows:
```python
class PydanticDefaultModel(BaseModel):
    model_config = ConfigDict(
        from_attributes=True,
    )
   
class PydanticBaseUser(PydanticDefaultsModel):
    email: Optional[EmailStr] = None
    is_active: Optional[bool] = True
    is_superuser: bool = False
    is_activated: bool = False
   
class PydanticUser(PydanticBaseUser):
    id: int
    
async def get_users(self) -> OffsetPagination[PydanticUser]:
    results, count = await self.list_and_count()
    return self.to_schema(data=results, total=count, schema_type=PydanticUser)
```

Thanks to @cofin for the last solution 🦋
