### ISSUE TITLE
Bug: multiple values for keyword arguments 

### ISSUE THREAD

**Issue by embecka** [litestar-org/litestar#3593]
### Description

Function parameters clashes with keyword arguments in [this function ](https://github.com/litestar-org/litestar/blob/31bc080deaf3607acbe6bf293b2015238505c800/litestar/routes/http.py#L191) or in [another]( https://github.com/litestar-org/litestar/blob/de8f4a77ff1ef2095e2dc2657b77b9b866322d3f/litestar/_signature/model.py#L209). More places in the source code may be affected.

One possible solution is to declare `kwargs` argument as `kwargs: dict[str, Any]` instead of `**kwargs: Any` to separate those namespaces.

### MCVE

```python
from litestar import Litestar, get


async def provide_connection() -> str:
    return "connection"


@get('/connection', dependencies={"connection": provide_connection})
async def get_connection(connection: str) -> str:
    return connection


async def provide_deserializer() -> int:
    return "deserializer"


@get('/deserializer', dependencies={"deserializer": provide_deserializer})
async def get_deserializer(deserializer: int) -> str:
    return deserializer


app = Litestar(route_handlers=[get_connection, get_deserializer])
```

### Steps to reproduce

```bash
1. Request the endpoint 'http://127.0.0.1:8000/connection'
2. Request the endpoint 'http://127.0.0.1:8000/deserializer'
```

### Logs

```bash
Traceback (most recent call last):
  File "/home/embe/anaconda3/envs/py312/lib/python3.12/site-packages/litestar/middleware/_internal/exceptions/middleware.py", line 158, in __call__
    await self.app(scope, receive, capture_response_started)
  File "/home/embe/anaconda3/envs/py312/lib/python3.12/site-packages/litestar/_asgi/asgi_router.py", line 99, in __call__
    await asgi_app(scope, receive, send)
  File "/home/embe/anaconda3/envs/py312/lib/python3.12/site-packages/litestar/routes/http.py", line 80, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/embe/anaconda3/envs/py312/lib/python3.12/site-packages/litestar/routes/http.py", line 132, in _get_response_for_request
    return await self._call_handler_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/embe/anaconda3/envs/py312/lib/python3.12/site-packages/litestar/routes/http.py", line 152, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/embe/anaconda3/envs/py312/lib/python3.12/site-packages/litestar/routes/http.py", line 191, in _get_response_data
    parsed_kwargs = route_handler.signature_model.parse_values_from_connection_kwargs(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: litestar._signature.model.SignatureModel.parse_values_from_connection_kwargs() got multiple values for keyword argument 'connection'






Traceback (most recent call last):
  File "/home/embe/anaconda3/envs/py312/lib/python3.12/site-packages/litestar/_signature/model.py", line 201, in parse_values_from_connection_kwargs
    return convert(kwargs, cls, strict=False, dec_hook=deserializer, str_keys=True).to_dict()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
msgspec.ValidationError: Expected `int`, got `str` - at `$.deserializer`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/embe/anaconda3/envs/py312/lib/python3.12/site-packages/litestar/middleware/_internal/exceptions/middleware.py", line 158, in __call__
    await self.app(scope, receive, capture_response_started)
  File "/home/embe/anaconda3/envs/py312/lib/python3.12/site-packages/litestar/_asgi/asgi_router.py", line 99, in __call__
    await asgi_app(scope, receive, send)
  File "/home/embe/anaconda3/envs/py312/lib/python3.12/site-packages/litestar/routes/http.py", line 80, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/embe/anaconda3/envs/py312/lib/python3.12/site-packages/litestar/routes/http.py", line 132, in _get_response_for_request
    return await self._call_handler_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/embe/anaconda3/envs/py312/lib/python3.12/site-packages/litestar/routes/http.py", line 152, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/embe/anaconda3/envs/py312/lib/python3.12/site-packages/litestar/routes/http.py", line 191, in _get_response_data
    parsed_kwargs = route_handler.signature_model.parse_values_from_connection_kwargs(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/embe/anaconda3/envs/py312/lib/python3.12/site-packages/litestar/_signature/model.py", line 209, in parse_values_from_connection_kwargs
    for field_name, exc in cls._collect_errors(deserializer=deserializer, **kwargs):  # type: ignore[assignment]
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: litestar._signature.model.SignatureModel._collect_errors() got multiple values for keyword argument 'deserializer'
```

### Litestar Version

2.9.0

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3593">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3593/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3593/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Hi @embecka! This is not a bug but a conscious design decision. It is documented [here](https://docs.litestar.dev/latest/usage/routing/handlers.html#reserved-keyword-arguments). 

Litestar considers these parameters "reserved" for use by Litestar itself. To resolve possible naming issues, you can simply provide an alternative injection name for your parameters. In case of the dependencies, this would simply mean using a different name, and for other parameters, the [docs have a link how to use the renaming feature](https://docs.litestar.dev/latest/usage/routing/parameters.html#alternative-names-and-constraints)

**Comment by provinzkraut** [comment]
Sorry for the confusion @embecka, I should have read your example more carefully. Yes, this is indeed a bug and your suggestion would be the proper fix :)
